#+TITLE: Math analysis
#+AUTHOR: Dmitry Mukhutdinov
#+DATE: [2014-11-12 Wed]
#+TODO: DUNNO LEARNING | LEARNED

* Definitions
** LEARNED o(h) при h -> 0
   CLOSED: [2014-11-12 Wed 15:16]
   f = o(h) при h → 0, если f/h → 0 при h → 0
** LEARNED Дифференцируемое отображение
   CLOSED: [2014-11-13 Thu 13:26]
   f: E ∈ ℝᵐ → ℝˡ, a ∈ Int(E)
   f - дифф-ма в т. a, если
   ∃ лин. оп. L : ℝᵐ → ℝˡ, такой, что f(a + h) = f(a) + L(h) + o(h) при h → 0
** LEARNED Производный оператор
   CLOSED: [2014-11-13 Thu 13:26]
   Это оператор L, который подходит под предыдущее определение
** LEARNED Матрица Якоби
   CLOSED: [2014-11-13 Thu 13:27]
   Матрица производного оператора
** LEARNED Дифференциал отображения
   CLOSED: [2014-11-14 Fri 02:26]
   F: ℝᵐ → ℝˡ, a ∈ Int(E), F дифф-ма в a.
   Дифференциал отобр-я F это:
   1) D : ℝᵐ → ℝˡ;
      D : h → F'(a)·h
   2) D : V(a) × ℝᵐ → ℝˡ;
      D : (x, h) → F'(x)·h
** LEARNED Частные производные
   CLOSED: [2014-11-13 Thu 13:27]
   F: ℝʳ → ℝ, a = (a₁, a₂, .. aᵣ), i ∈ [1..r]
   Зададим функции fᵢ(t) = F(a₁, a₂, .. t, .. aᵣ)
   fᵢ'(aᵢ) = lim (fᵢ(aᵢ + h) - fᵢ(aᵢ))/h, h → 0
   Если ∃ fᵢ', то тогда функция Fₓᵢ'(a) = fᵢ'(aᵢ) - частная производная F по xᵢ
** LEARNED Производная по вектору, направлению
   CLOSED: [2014-11-14 Fri 02:26]
   l ∈ ℝᵐ, |l| = 1 ⇒ l - направление
   Част. производная ф-ции F по направлению в точке a -
   δF/δl(a) = lim (F(a + tl) - F(a))/t, t → 0
** LEARNED Градиент
   CLOSED: [2014-11-13 Thu 18:19]
   F: ℝʳ → ℝˡ, a ∈ Int(E), F дифф-ма в a.
   ⇒ F(a + h) = F(a) + F'(a)·h + o(h) = F(a) + <u, h> + o(h)
   u = (grad F)(a) = (fₓ₁', fₓ₂', .. fₓᵣ)·a
** LEARNED Частная производная 2-го порядка, k-го порядка
   CLOSED: [2014-11-13 Thu 13:52]
   Пусть g = Fₓ₁' - частная производная F по x₁
   Тогда gₓ₂' = Fₓ₁ₓ₂'' - част. производная F 2-го порядка
   По индукции: Fₓ₁ₓ₂..ₓᵢ⁽ⁱ⁾ - част. производная i-го порядка
** LEARNED Классы Cʳ(E)
   CLOSED: [2014-11-13 Thu 13:38]
   Сʳ(E) = {∀ F : E → R | ∀ i = 1..r : ∀ j : Fₓⱼ⁽ⁱ⁾ существует и непрерывна }
** LEARNED Мультииндекс и обозначения с ним
   CLOSED: [2014-11-14 Fri 02:31]
   Мультииндекс i = (i₁, i₂,...iᵣ).
   Высота мультииндекса: |i| = i₁ + i₂ + ... + iᵣ
   i! = i₁! · i₂! · ... · iᵣ!
   aⁱ = aⁱ¹ · aⁱ² · ... · aⁱʳ
   F⁽ⁱ⁾ = (δ^|i| F) / (δx₁ⁱ¹ δx₂ⁱ² ... δxᵣⁱʳ)
   (a₁ + a₂ + ... + aᵣ)ᵏ = ∑ (k! / i!) aⁱ, for i : |i| = k
** LEARNED Формула Тейлора и различные виды записи
   CLOSED: [2015-04-22 Wed 14:01]
   f: E ⊂ ℝᵐ → ℝ, r ∈ ℕ, f ∈ Cʳ⁺¹(E)
   a ∈ E, B(a, ρ) ⊂ E. ТОГДА функцию можно записать в виде ряда Тейлора:
   ∀ x ∈ B(a, ρ) ∃ t ∈ (0, 1) :
   f(x) = ∑₀ⁿ(∑ (1/i!) f⁽ⁱ⁾(a)(x - a)ⁱ, i: |i| = r) + (∑ (1/i!) f⁽ⁱ⁾(a + t(x - a))(x - a)ⁱ, i: |i| = r + 1)
** LEARNED n-й дифференциал
   CLOSED: [2015-04-22 Wed 14:01]
   n-й дифференциал функции f в точке a:
   dⁿf(a, h) = ∑ (n!/i!) f⁽ⁱ⁾(a) hⁱ , i: |i| = n
** LEARNED Норма линейного оператора
   CLOSED: [2014-11-14 Fri 02:32]
   A ∈ L(X, Y) - лин. оператор, A : X → Y
   ∥A∥ = sup |Ax|, x ∈ X, |x|ₓ ≤ 1
** LEARNED Положительно-, отрицательно-, незнакоопределенная квадратичная форма
   CLOSED: [2014-11-14 Fri 02:35]
   L - лин. пространство, K - поле, Q : L -> K - квадратичная форма, если:
   Q(x) = ∑ aᵢⱼxᵢxⱼ, x = (x₁, x₂...xᵣ) ∈ L
   {aᵢⱼ} - матрица кв. формы
   Положительно определенная - везде > 0, кроме 0
   отрицательно - < 0, кроме 0
** LEARNED Локальный максимум, минимум, экстремум
   CLOSED: [2014-11-13 Thu 19:43]
   f: ℝᵐ → ℝ
   x₀ - локальный максимум ф-ции f, если
   ∃ V(x₀) : ∀ x ∈ V(x₀) f(x) ≤ f(x₀)
   Минимум - то же самое, только ≥
   Экстремум - либо то, либо другое
** LEARNED Диффеоморфизм
   CLOSED: [2014-11-14 Fri 02:34]
   Пусть O ⊂ ℝᵐ - открыто и связно
   D: O → K ⊂ ℝᵐ - диффеоморфизм, если D дифф-емо и D⁻¹ существует и дифф-емо
** LEARNED Формулировка теоремы о локальной обратимости в терминах систем уравнений
   CLOSED: [2014-11-14 Fri 12:32]
   Есть система уравнений: { f₁(x₁, x₂...xᵣ) = y₁, ... fᵣ(x₁, x₂...xᵣ) = yᵣ }
   Пусть (x₁⁰,...xᵣ⁰, y₁⁰,...yᵣ⁰) - решение, иначе запишем: (x⁰, y⁰)
   Если ∀ i: fᵢ - гладкие в V(x⁰) и det (δfᵢ/δxⱼ (x⁰)) ≠ 0, ТОГДА:

   ∃ U(y⁰), V(x⁰) ∀ y ∈ U(x⁰) система разрешима, и ∃! решение в V(x⁰): xᵢ(y₁...yᵣ), причем это решение гладкое.
** LEARNED Формулировка теоремы о неявном отображении в терминах систем уравнений
   CLOSED: [2015-01-08 Чт. 19:51]
   Пусть дана система: { f₁(x₁...xᵤ, y₁...yᵥ) = 0, ... fᵥ(x₁...xᵤ, y₁...yᵥ) = 0 }
   Пусть (x⁰, y⁰) - решение системы.
   Если ∀ i: fᵢ - гладкие в V(x⁰, y⁰) и det( δfᵢ/δyⱼ (x⁰, y⁰) ) ≠ 0, ТОГДА:

   ∃ P(x⁰), Q(y⁰) ∀ x ∈ P(x⁰) система разрешима, и ∃! решение в Q(y⁰), и это решение yᵢ(x₁..xᵤ) - гладкое,
   причем δyᵢ/δxⱼ (x⁰) = - ∑ᵤ(δfᵤ/δyᵢ(x⁰, y⁰) · δfᵤ/δxⱼ(x⁰, y⁰))
** LEARNED Гладкое простое k-мерное многообразие в ℝᵐ
   CLOSED: [2015-01-08 Чт. 19:50]
   Подмножество ℝᵐ, в которое существует гладкое всюду невырожденное отображение
   из некоторого подмножества ℝᵏ

   M ⊂ ℝᵐ
   1) M - простое k-мерное многообразие, если ∃ f: O ⊂ ℝᵏ → M
   2) M - r-гладкое, если f ∈ Cʳ(O, ℝᵐ) и ∀ x ∈ O: Rg f'(x) = k
** LEARNED Относительный локальный максимум, минимум, экстремум
   CLOSED: [2015-04-22 Wed 14:01]
   Относительный локальный максимум - локальный максимум среди всех точек,
   удовлетворяющих какому-либо условию.
   Иначе: относительный локальный максимум - это локальный максимум на точках какого-либо
   гладкого многообразия.

   Ф : E ⊂ ℝᵐ⁺ᵏ → ℝᵏ,
   f : E → ℝ  - гладкие функции

   Относительный локальный максимум функции f при условии Ф = 0 - это такая
   точка a, что:
   1) Ф(a) = 0
   2) ∃ V(a) : ∀ x ∈ V(a), Ф(x) = 0 : f(x) ≤ f(a)

   Минимум, строгость/нестрогость, экстремум - аналогично.
** LEARNED Формулировка достаточного условия относительного экстремума
   CLOSED: [2015-04-22 Wed 14:01]
   Если дифференциал функции Лагранжа зануляется в точке, то проверяем второй дифференциал
   (с условием, что перемещаемся мы только вдоль нашего многообразия)

   f: E ⊂ ℝᵐ⁺ⁿ → ℝ, Ф: E → ℝⁿ - гладкие функции.
   a ∈ E, Ф(a) = 0, Rg Ф'(a) = n,
   ∃ λ ∈ ℝⁿ: F(x) := f(x) - λФ(x), такая, что:
   1) dF(a) = 0
   2) Q(h) = d²F(a, h) - квадратичная форма, Q: ℝᵐ⁺ⁿ → ℝ
      Построим Q': ℝᵐ → ℝ, Q'(h₁..hₘ) = Q(h₁..hₘ, hₘ₊₁(h₁..hₘ) .. hₙ(h₁..hₘ))
      Если Q' - положит. определена, то a - относ. min
      Если Q' - отриц. определена, то а - относ. max
      Если незнакоопределена - то не экстремум.
** LEARNED Кусочно-гладкий путь
   CLOSED: [2015-01-08 Чт. 20:23]
   Кусочно-гладкий путь - путь, гладкий везде, кроме конечного множества точек.

   γ : [a, b] → ℝⁿ - путь в ℝⁿ, {xₖ} ⊂ [a, b] - конечный набор
   γ ∈ C¹([a, b] \ {xₖ})
** LEARNED Интеграл векторного поля по кусочно-гладкому пути
   CLOSED: [2015-01-08 Чт. 20:23]
   Интеграл векторного поля по пути - это РАБОТА этого поля по
   ПЕРЕМЕЩЕНИЮ точки вдоль пути)) (значение поля скалярно на скорость в каждой точке)

   γ : [a. b] → E ⊂ ℝᵐ - кусочно-гладкий путь
   V ∈ C⁰(E, ℝᵐ) - векторное поле
   I(V. γ) = ₐ∫ᵇ <V(γ(t)), γ'(t)> dt
** LEARNED Потенциальное векторное поле
   CLOSED: [2015-01-08 Чт. 20:24]
   Потенциальное поле - поле, имеющее потенциал))
** LEARNED Потенциал векторного поля
   CLOSED: [2015-01-08 Чт. 20:24]
   Потенциал векторного поля - функция, градиент которой задает векторное поле.

   V: O ⊂ ℝᵐ → ℝᵐ - векторное поле,
   Если ∃ f: O → ℝ, такая, что ∀ x ∈ O: V(x) = <grad f, x>
** LEARNED Локально-потенциальное векторное поле
   CLOSED: [2015-01-08 Чт. 20:24]
   Поле, которое имеет потенциал отдельно в любой окрестности любой точки.

   V: O ⊂ ℝᵐ → ℝᵐ. Если ∀ x ∈ O ∃ U(x) : V потенциально в U(x), то V - локально-потенциально.
** LEARNED Похожие пути
   CLOSED: [2015-01-08 Чт. 20:24]
   Два пути похожи, если они имеют общую гусеницу

   γ, γ' : [a. b] → ℝᵐ - похожие, если ∃ дробление a = t₀ ≤ .. ≤ tₙ = b,
   и ∃ Bₖ - посл-ть шаров: ∀ k ∈ {1..n}: γ[tₖ₋₁, tₖ] ⊂ Bₖ, γ'[tₖ₋₁, tₖ] ⊂ Bₖ
** LEARNED Гусеница
   CLOSED: [2015-01-08 Чт. 20:24]
   Набор шаров, покрывающий путь согласно его разбиению.

   γ : [a. b] → ℝᵐ - непрерывный путь, a = t₀ ≤ .. ≤ tₙ = b - его дробление,
   Гусеница - посл-ть шаров Bₖ : ∀ k ∈ {1..n}: γ[tₖ₋₁, tₖ] ⊂ Bₖ, γ'[tₖ₋₁, tₖ] ⊂ Bₖ
** LEARNED Интеграл локально-потенциального векторного поля по произв. пути
   CLOSED: [2015-01-08 Чт. 20:49]
   Интеграл по кусочно-гладкому пути, близкому к данному (похожему с ним)
** LEARNED Гомотопия путей: связанная и петельная
   CLOSED: [2015-01-08 Чт. 20:49]
   Гомотопия 2 путей - это плавный переход из 1 пути в другой.
   Пути гомотопны, если этот переход можно осуществить.

   γ₀, γ₁ : [a, b] → X - пути.
   Гомотопия γ₀ и γ₁ - отобр-е Г : [a, b] × [0, 1] → X, такое, что:
   а) Г непрерывно
   б) ∀ t ∈ [a, b] : Г(t, 0) = γ₀(t), Г(t. 1) = γ₁(t)

   Связанная гомотопия - это когда у путей совпадают начало и конец, и у всех
   промежуточных путей тоже.

   Петельная гомотопия - это когда пути являются петлями, и все промежуточные пути
   тоже.
** LEARNED Односвязная область
   CLOSED: [2015-01-08 Чт. 20:49]
   Односвязная область - область, в которой любую петлю можно стянуть в точку.

   Мн-во O - односвязно ⇔ ∀ γ : [a, b] → O, γ(a) = γ(b) ∃ γ': [a, b] → O:
   ∀ x ∈ [a, b] γ'(x) = γ(a), γ и γ' - петельно гомотопные пути
** LEARNED Полукольцо
   CLOSED: [2015-04-23 Thu 21:37]
   Штука, сожержащая пустое множество, все пересечения ее элементов, а так же
   всякая разница элементов составлена из какого-то дизъюнктного набора.

   Полукольцо подмножеств - это P ⊂ 2ˣ, такое, что
   1) ∅ ∈ P
   2) ∀ A, B ∈ P : A ∩ B ∈ P
   3) ∀ A ⊂ B ∈ P : ∃ D₁..Dᵣ - дизъюнкт. набор: B \ A = ⊔ Dᵢ

** LEARNED Алгебра
   CLOSED: [2015-04-23 Thu 21:37]
   Уже лежит все множество X и всякая разница 2 множеств тоже уже лежит

   ℵ ⊂ 2ˣ - алгебра, если:
   1) ∀ A, B ∈ ℵ : A ﹨ B ∈ ℵ
   2) X ∈ ℵ
** LEARNED Сигма-алгебра
   CLOSED: [2015-04-24 Fri 09:46]
   Любое счетное объединение элементов лежит в сигма-алгебре

   ℵ - σ-алгебра, если:
   1) ℵ - алгебра
   2) ∀ A₁, A₂... ∈ ℵ - счетный набор мн-в, ∪Aᵢ ∈ ℵ
** LEARNED Объем
   CLOSED: [2015-04-23 Thu 21:37]
   Положительная конечно-аддитивная функция на полукольце

   Пусть P - полукольцо
   μ : P → ℝ⁺ - объем, если:
   1) μ конечно аддитивен (∀ A₁..Aᵣ ∈ P - кон. дизъюнкт. набор,
      ⊔ Aᵢ = A : μ(A) = ∑ μ(Aᵢ))
   2) μ(∅) = 0
** LEARNED Мера
   CLOSED: [2015-04-23 Thu 21:37]
   Мера - это счетно-аддитивный объем
** LEARNED Сигма-конечный объем
   CLOSED: [2015-04-24 Fri 01:53]
   Сигма-конечный объем - такой объем, при котором все множество
   можно представить в виде счетного объединения множеств конечного объема.

   P ⊂ 2ˣ - полукольцо
   μ : P → ℝ⁺ - объем
   μ - σ-конечен, если ∃ A₁, A₂.. - счетный набор мн-в. : ∀ i : μ(Aᵢ) < ∞, ∪ Aᵢ = X
** LEARNED Сигма-конечная мера
   CLOSED: [2015-04-24 Fri 01:53]
   То же самое, что σ-конечный объем, только мера
** LEARNED Полная мера
   CLOSED: [2015-04-23 Thu 21:37]
   Мера полна, если при ней любое подмножество множества нулевой меры
   также имеет нулевую меру.

   μ : P -> ℝ⁺ - мера,
   μ - полная мера, если ∀ A ∈ P, μ(A) = 0 : ∀ B ⊂ A , B ∈ P : μ(B) = 0
** LEARNED Мера Лебега
   CLOSED: [2015-04-23 Thu 21:37]
   Мера Лебега - результат Лебеговского продолжения классического объема на сигма-алгебру
** LEARNED Борелевская сигма-алгебра в ℝᵐ
   CLOSED: [2015-04-23 Thu 21:37]
   Борелевская σ-алгебра - наименьшая σ-алгебра, вкл. в себя все открытые подмножества ℝᵐ
   иначе:

   ℵ₀ ⊂ 2ʳᵐ - σ-алгебра
   ℵ₀ - борелевская σ-алгебра, если:
   Q = { ∀ A : A ⊂ X, A - открыто } ⊂ ℵ₀;
   ∀ ℵ ⊂ 2ʳᵐ, ℵ - σ-алгебра, Q ⊂ ℵ : ℵ₀ ⊆ ℵ

** LEARNED Формулировка теоремы о мерах, инвариантных относительно сдвигов
   CLOSED: [2015-04-24 Fri 01:54]
   Меры, инвариантные относительно сдвига, отличаются от меры Лебега на константу

   Пусть Pᵐ ⊂ ℵ ⊂ Mᵐ, μ - мера на ℵ, μ - инв. отн. сдвига, т. е.:
   ∀ T - сдвиг, ∀ A ∈ ℵ : T(A) ∈ ℵ, μ(A) = μ(T(A))
   Тогда ∃ C > 0 : ∀ A ∈ ℵ : μ(A) = C · λ(A)

** LEARNED Мера Лебега-Стилтьеса, мера Бореля-Стилтьеса
   CLOSED: [2015-04-24 Fri 09:48]
   Мера Лебега-Стильеса - это мера на ℝ, определяемая разностью значений
   некоторой возрастающей непрерывной функции на концах отрезка

   g: ℝ → ℝ - возр., непр.;
   μ[a, b) = g(b) - g(a) - конечно-аддитивный объем и мера.
   мера Лебега-Стильеса - результат лебеговского продолжения μ

   Мера Бореля-Стильеса - сужение меры Лебега-Стильеса на борелевскую сигма-алгебру
** LEARNED Ступенчатая функция
   CLOSED: [2015-04-22 Wed 14:09]
   Ступенчатая функция - это у которой график ступеньками))

   f: X → ℝ - ступенчатая функция, если ∃ ⊔Xᵢ = X: f|ₓᵢ = Cᵢ (константа)
** LEARNED Разбиение, допустимое для ступенчатой функции
   CLOSED: [2015-04-22 Wed 14:11]
   Любое разбиение X, подходящее под предыдущее определение (дизъюнктное, покрывающее все X)
** LEARNED Измеримая функция
   CLOSED: [2015-04-22 Wed 14:14]
   Функция такая, что все Лебеговы множества этой функции измеримы данной мерой.

   Лебегово множество E(f < a) - это множество, на котором выполняется условие внутри скобок.

   (X, ℵ. μ) - пр-во с мерой
   f: X → ℝ - измерима, если ∀ a ∈ ℝ: X(f < a), X(f ≤ a), X(f > a), X(f ≥ a) ∈ ℵ

** LEARNED Свойство, выполняющееся почти везде
   CLOSED: [2015-04-22 Wed 14:14]
   Свойство, выполняющееся везде. кроме множества точек нулевой меры.

   P: E → Bool - свойство, E - мн-во. P(x) почти везде на E,
   если P(x) ∀ x ∈ E \ X, μ(X) = 0

** LEARNED Сходимость почти везде
   CLOSED: [2015-04-22 Wed 14:14]
   Ровно по предыдущему опр-ю.

   fₙ → f почти везде на E, если X ⊂ E, μX = 0,
   ∀ x ∈ E \ X : fₙ(x) → f(x)

** LEARNED Сходимость по мере
   CLOSED: [2015-04-24 Fri 02:05]
   fₙ сходится к f по мере, если всякое Лебегово множество их разности стремится к нулю.

   fₙ, f - измеримы на мн-ве Е. ∀ δ > 0: E(|fₙ - f| ≥ δ) - измеримо
   fₙ ⇒ f по мере μ на мн-ве Е, если ∀ δ > 0: μE(|fₙ - f| ≥ δ) → 0.
** LEARNING Теорема Егорова о сходимости почти везде и почти равномерной сходимости
   Если fₙ, f измеримы почти везде **конечной** мерой и fₙ → f почти везде, то
   эта сходимость "почти равномерна", что значит:

   (X, ℵ, μ), μX < +∞, fₙ → f почти везде на X
   ∀ ε > 0 ∃ E ⊂ X, E - измеримо, μE < ε : fₙ ⇉ f на X \ E
** LEARNED Интеграл ступенчатой функции
   CLOSED: [2015-04-22 Wed 14:14]
   Интеграл ступенчатой функции - сумма площадей ступенек ))

   (X, ℵ, μ). f : X → ℝ - ступ. функция, f = ∑ aᵢₑᵢ
   ₓ∫f dμ = ∑ aᵢ · μ(Eᵢ ∩ X)
** LEARNED Интеграл неотрицательной измеримой функции
   CLOSED: [2015-04-22 Wed 14:14]
   Это супремум интегралов всех ступенчатых функций, меньших данной.

   (X, ℵ, μ). f - изм. на X
   ₓ∫ fdμ = sup { ₓ∫ gdμ | g - ступ. ф-ция, 0 ≤ g ≤ f }
** LEARNED Суммируемая функция
   CLOSED: [2015-04-22 Wed 14:14]
   Суммируемая функция - измеримая функция, у которой интегралы для обоих срезок
   определены и конечны.

** LEARNED Интеграл суммируемой функции
   CLOSED: [2015-04-22 Wed 14:15]
   Разница интегралов срезок

   (X, ℵ, μ). f - суммируема на X.
   ₓ∫fdμ = ₓ∫f₊dμ - ₓ∫f₋dμ
** LEARNED Условие Lₗₒₖ
   CLOSED: [2015-04-24 Fri 02:08]
   В любой окрестности y₀ функция ограничена сверху какой-то суммируемой функцией, не зависящей от y

   Функия f удовлетворяет условию Lₗₒₖ(y₀) если
   ∀ U_{y₀} : ∃g(x) - суммируемая : ∀y ∈ U_{y₀}, ∀x, |f(y, x)| ≤ g(x) и g(x) суммируемая
** LEARNING Образ меры при отображении
   Образ меры при отображении - новая мера, которая получается применением ко множеству
   обратного отображения и старой меры.

   (X, ℵ, μ), (Y, ℶ, _)
   Пусть есть отображение Ф:X → Y, причем
   Φ⁻¹(ℶ) = {Φ⁻¹(B), B ∈ ℶ}, Φ⁻¹(ℶ) ⊆ ℵ
   тогда ∀B ∈ ℶ ν(B) = μ(Φ⁻¹(B)) -- это образ меры при отображении
** LEARNING Взвешенный образ меры
   Взвешенный образ меры - это мера, которая представляет собой интеграл весовой
   функции по прообразу аргумента по старой мере.

   (X, ℵ, μ), (Y, ℶ, _)
   w - вес, w ≥ 0, измерима,
   Φ: X → Y, Φ⁻¹(ℶ) ∈ ℵ
   ν(B) = ∫_Φ⁻¹(B) wdμ - взвешенный образ меры μ
** LEARNED Плотность одной меры по отношению к другой
   CLOSED: [2015-04-23 Thu 22:09]
   Если есть две меры на одной и той же алгебре, и одна из них - взвешенный образ
   этой меры с отображением id, тогда весовая функция второй меры - это и есть
   плотность этой меры относительно другой.

   X = Y, ℵ = ℶ, Φ = id,
   w - вес, положительная измеримая ф-я,
   f - измеримая на X
   ν(B) = ∫_B wdμ, ∫fdν=∫f(x)w(x)dμ
   тогда вес w - это плотность ν относительно μ.
** LEARNED Заряд
   CLOSED: [2015-04-22 Wed 14:25]
   Это такая мера, которая может быть отрицательной

   (X, A)
   μ: A → ℝ, μ - счет. аддитивна, μ(∅) = 0 -- это заряд, не обязан быть ≥ 0
** LEARNED Множество положительности заряда
   CLOSED: [2015-04-23 Thu 22:10]
   Кусок алгебры, на котором заряд положителен.

   (X, A, μ)
   B ∈ A -- множество положительности заряда, если ∀ E ∈ B : μE ≥ 0
** LEARNED Мера абсолютно непрерывная относительно другой
   CLOSED: [2015-04-24 Fri 09:57]
   Мера абсолютно непрерывна отн. другой, если она возвращает 0 везде,
   где это делает первая

   ν абсолютно непрерывна относительно μ, если
   ∀ a : μ(a) ≡ 0 ⇒ ν(a) ≡ 0
** LEARNED Произведение мер
   CLOSED: [2015-04-23 Thu 22:11]
   Мера на декартовых произведениях пространств, которая равна произведению 2 мер от компонентов
   декартова произведения.

   Пример: l - мера длины, s - мера площади, тогда V = sl - мера объема

   (X, ℵ, μ), (Y, ℶ, ν)
   X × Y - декартово произведение,
   ℵ × ℶ = {A × B | A ∈ ℵ, B ∈ ℶ} - полукольцо обобщенных прямоугольников
   m : ℵ × ℶ → ℝ⁺, m(A × B) = μ(A)ν(B)
   Тогда (X × Y, ℵ × ℶ, m) - пространство с мерой, и m - произведение мер μ и ν
** LEARNED Сечение множества
   CLOSED: [2015-04-23 Thu 22:15]
   Пусть есть множество в ℝ³, вот ее срез по определенному x₀ - это множество в ℝ²,
   которое называется сечением фигуры по x₀

   Пусть у нас есть C ⊂ X × Y, тогда
   Cₓ = {y ∈ Y | (x, y) ∈ C}
   Cy = {x ∈ X | (x, y) ∈ C}
** LEARNING Функция распределения
   Мера множества, на котором функция меньше аргумента.

   (X, §ℶ, μ), h: X → ℝ, X(h < x) конечно, тогда H(x) = μX(h < x)

** LEARNING Интегральные неравенства Гёльдера и Минковского
   p, q > 1, 1/p + 1/q = 1; f, g - измеримы* и п.в. конечны.

   ∫|fg| ≤ (∫|f|ᵖ)^(1/p) · (∫|g|^q)^(1/q) - неравенство Гёльдера

   p ≥ 1
   (∫|f + g|ᵖ)^(1/p) ≤ (∫|f|ᵖ)^(1/p) + (∫|g|ᵖ)^(1/p) - неравенство Минковского

   Оно задает норму на функциях: |f + g| ≤ |f| + |g|
** LEARNING Интеграл комплекснозначной функции
   f : X → C⁺ (комплексные числа + ∞)
   1) f - измерима, если Re f и Im f - измеримы
   2) ∫f = ∫Re f + i∫Im f, f - суммируема, если Re и Im суммируемы
** LEARNING Пространство Lᵖ(E, μ)
   Линейное пространство классов измеримых функций с нормой Минковского с параметром p.

   {f: X → C⁺, f - изм, (∫|f|ᵖ)^(1/p) < +∞} - нормированное Л.П. в силу нер-ва Минковского
   там есть 0 - любая п.в. нулевая функция.
   Возьмем это пространство и факторизуем его по отношению равенства почти везде.
   Получится пространство Lᵖ
** LEARNING Пространство L∞(E, μ)
   Линейное пространство классов существенно ограниченных измеримых функций

   L∞ = ({f - изм, esssup f < +∞})⁼, где (·)⁼ - факторизация по отн. равенства почти везде.
** LEARNED Существенный супремум
   CLOSED: [2015-06-25 Thu 18:41]
   Существенный супремум - супремум почти везде.

   esssup f = {M ∈ ℝ⁺, f(x) ≤ M почти везде}
** LEARNING Фундаментальная последовательность, полное пространство
   Фундаментальная последовательность - сходящаяся в себе

   Пусть X - норм. пространство, xₙ ∈ X - фундаментальная последовательность, если
   ∀ ε > 0 ∃ N ∀ n, m > N : |xₙ - xₘ| < ε

   Полное пространство - это где любая фунд. последовательность сходится

   X - полно, если ∀ xₙ - фунд. посл-ть : ∃ lim xₙ ∈ X
** LEARNING Плотное множество
   Множество всюду плотно, если оно пересекается с любым открытым множеством.

   X - метр. пр-во. A ⊂ X - (всюду) плотно на X, если ∀ O ⊂ X - открытое мн-во,
   O ∩ A ≠ ∅
** LEARNED Финитная функция
   CLOSED: [2015-06-25 Thu 20:31]
   f - финитна, если f = 0 за пределами некоторого шара.
** LEARNED Гильбертово пространство
   CLOSED: [2015-06-26 Fri 00:10]
   Гильбертово пространство - полное линейное пространство со скалярным произведением
   (полное унитарное пространство)
** LEARNED Ортогональная система, ортонормированная система векторов, примеры
   CLOSED: [2015-06-26 Fri 00:10]
   Ортогональная система - конечный набор попарно ортогональных векторов
   Ортонормированная - это когда все вектора еще и имеют длину 1.
   Примеры:
   1) Стандартный базис (вектора с единичками)
   2) В пространстве L²[-π, π] : тригонометрический базис: {1, sinx, cosx, sin2x, cos2x, ...}
      а если поделить на sqrt(π) (единицу - еще и на 2), получится ортонормированный
   3)

** LEARNED Сходящийся ряд в гильбертовом пространстве
   CLOSED: [2015-06-26 Fri 00:20]
   Ну, типа, ряд элементов гильбертова пространства, который сходится?
** LEARNED Ортогональная система (семейство) векторов
   CLOSED: [2015-06-26 Fri 00:16]
   Эм, ну 2 строки выше
** LEARNED Ортонормированная система
   CLOSED: [2015-06-26 Fri 00:16]
   Эм, ну вон тоже 3 строки выше
** LEARNING Коэффициенты Фурье
   Коэффициенты Фурье - это коэффициенты разложения по ортонормированной система
** LEARNING Ряд Фурье
   Ряд Фурье - это разложение вектора по ортонормированной системе
** LEARNING Базис, полная, замкнутая ОС
   Базис - ОС, через которую можно все выразить
   {eₖ} - базис, если ∀ x ∈ H : x = ∑Cₖ(x)eₖ
   Полная система - такая, которой ортогонален только ноль.
   {eₖ} - полная, если z ⊥ {eₖ} ⇒ z = 0
   Замкнутая система - такая, в которой норма разложения равна норме вектора
   {eₖ} - замкнутая, если ∀ x ∈ H : |x|² = ∑|Cₖ(x)|² · |eₖ|²
** LEARNING Тригонометрический ряд
   Тригонометрический ряд - ряд вида
   a₀/2 + ∑(aₖcoskx + bₖsinkx)
   (или в комплексном случае: ∑Cₖe⁻ⁱᵏˣ)
** LEARNING Коэффициенты Фурье функции
   Коэффициенты Фурье функции - это коэффициенты рядом с синусом и косинусом в разложении
   функции в тригонометрический ряд.

   f ∈ L¹[π, π], тогда aₖ(f), bₖ(f), Cₖ(f) - коэф-ты Фурье f,
   а ряд aₒ/2 + ∑aₖcoskx + ∑bₖsinkx (∑Cₖe⁻ⁱᵏˣ) - ряд Фурье этой функции
** LEARNING Ядро Дирихле, ядро Фейера
   1) Ядро Дирихле - функция Dₙ(t) = (1/π)·(1/2 + ∑ₖⁿ cos(kt))
   2) Ядро Фейера - функция Фₙ(t) = (1/(n+1)) · ∑ₖⁿDₖ(t)
** LEARNING Свертка
   Свертка двух функций - это интеграл, в котором одна функция как бы "наматывается"
   на другую вокруг данной точки
   f, K ∈ L¹[-π, π].
   Свертка - это ф-ция (f ⋆ K)(x) = ₋ₚᵢ∫ᵖⁱ f(t)K(x - t)dt = ₋ₚᵢ∫ᵖⁱ f(x - t)K(t)dt
** LEARNING Аппроксимативная единица
   Семейство функций, интеграл которых равен единице, интегралы норм ограничены,
   и при приближении параметра к некой точке интегралы норм сходятся к нулю

   Пусть D ⊂ ℝ, xₒ ∈ ℝ⁺, xₒ - предельная точка D.
   ∀ h ∈ D определена ф-ция Kₕ(x) со след. свойствами:
   1) Kₕ ∈ L¹[-π, π], ₋ₚᵢ∫ᵖⁱ Kₕ(t)dt = 1
   2) ∃ M ∀ h ∈ D : ∫|Kₕ| ≤ M
   3) ∀ δ > 0 : ₑ∫|Kₕ| → 0 при h → x₀

   Тогда семейство Kₕ называется аппроксимативной единицей
** LEARNING Усиленная аппроксимативная единица
   Усиленная аппроксимативная единица - это которая еще и существенно ограничена,
   и ее существенный супремум стремится к 0.

   Если Kₕ ∈ L∞[-π, π], esssup|Kₙ| → 0 при h → x₀. Тогда
   Kₕ - усиленная аппроксимативная единица
** LEARNING Метод суммирования средними арифметическими
   Вместо устремления частичных сумм к бесконечности устремляем средние
   арифметические частичных сумм

   ∑ аₙ (ср. ариф) = lim{n → ∞} (S₀ + S₁ + .. + Sₙ)/(n + 1)
** LEARNING Измеримое множество на простой двумерной поверхности в ℝ³
   Кусок простой двумерной поверхности измерим, если измерим его гладкий прообраз в ℝ²

   M - простая гл. 2-мерная пов. в ℝ³
   φ : Ω ⊂ ℝ² → ℝ³ - гладкая
   A ⊂ M - измеримо (по Лебегу), если φ⁻¹(A) - измеримо
** LEARNING Мера Лебега на проcтой двумерной поверхности в ℝ³
   Получаем меру как взвешенный образ обычной меры (с якобианом)

   σ(A) = Ф⁻¹(A)_∫ |det Ф'|dudv
** LEARNING Поверхностный интеграл первого рода
   A_∫fdS = Ф⁻¹(A)_∫f ∘ Ф sqrt(EG - F²)dudv
   где
   E = xᵤ'² + yᵤ'² + zᵤ'²
   G = xᵥ'² + yᵥ'² + zᵥ'²
   F = xᵤ'xᵥ' + yᵤ'yᵥ' + zᵤ'zᵥ'
** LEARNING Кусочно-гладкая поверхность в ℝ³
   Поверхность кусочно-гладкая, если она является объединением
   конечного числа простых гладких поверхностей
   конечного числа простых гладких дуг
   конечного числа отдельных точек
** LEARNING Сторона поверхности
   Сторона поверхности - нормальный вектор к ней.
** LEARNING Задание стороны поверхности при помощи касательных реперов
   Нормальный вектор выражается через 2 касательных

   nₒ(x) = (v₁(x) × v₂(x))/|v₁(x) × v₂(x)|
** LEARNING Интеграл второго рода
   Интеграл второго рода по поверхности - интеграл скалярного произведения векторного поля на сторону
   m∫<F, n₀>dσ
** LEARNING Ориентация контура, согласованная со стороной поверхности
   Такая ориентация контура, что соблюдается правило буравчика/правой руки для выбранной нормали
   к поверхности
** LEARNING Ротор, дивергенция векторного поля
   V = (P, Q, R)
   rot V = (R_y' - Q_z', P_z' - Rₓ', Qₓ' - P_y')
   div V = Pₓ' + Q_y' + R_z'
** LEARNING Соленоидальное векторное поле
   Поле соленоидальное, если для него существует векторный потенциал,
   то есть такое B, что V = rot B
* Theorems
** LEARNED Единственность производной
   CLOSED: [2014-11-13 Thu 20:14]
   Производный оператор F в точке a единственен.

   ▷
   Зафиксируем вектор a, примем h = ta и устремим t к нулю;
   единственность вытекает из единственности предела.
   ∎
** LEARNED Лемма о покоординатной дифференцируемости
   CLOSED: [2015-01-08 Чт. 15:15]
   Векторнозначная функция диф-ма тогда и только тогда, когда диф-мы все ее компоненты

   F: ℝᵐ → ℝʳ
   1) F дифф-ма тогда и только тогда, когда дифф-мы все ее коорд. ф-ции F₁...Fᵣ
   2) Матрица Якоби ф-ции F - это матрицы Якоби ф-ций F₁...Fᵣ, положенные друг на друга

   ▷
   Разбиваем определение дифференцируемости на строки в векторах (или наоборот)
   ∎
** LEARNED Необходимое условие дифференцируемости
   CLOSED: [2014-11-14 Fri 11:26]
   Если функция дифференцируема в точке, то все ее частные производные в этой точке существуют

   F: ℝʳ → ℝ.
   F - дифф-ма ⇒
     1) ∃ все част. производные Fₓᵢ'
     2) F'(a) = (Fₓ₁'(a), ... Fₓᵣ'(a))

   ▷
   Подставляем в определение дифф-сти h = (0, 0.. t .. 0) (t - на k-ой позиции)
   Пошафлим и получим определения частной произв.
   ∎
** LEARNED Достаточное условие дифференцируемости
   CLOSED: [2014-11-14 Fri 11:26]
   Функция дифференцируема в точке А, если все ее част. производные существуют и непрерывны в т. А

   F: E ⊂ ℝʳ → ℝ, a ∈ Int(E)
   Тогда, если ∃ V(a) ∀ x ∈ V(a) ∃ Fₓ₁'(x) ... Fₓᵣ'(x), и все эти производные непрерывны в a,
   то F - дифференцируема в т. a

   ▷
   Рассматриваем r = 2. Вычитаем-прибавляем функцию на частично прибавленных аргументах.
   Получившиеся разности меняем на частные производные по т. Лагранжа, вытаскиваем мусор из скобочек
   наружу в эпсилон из определения непрерывности. Переходим к пределу и получаем определение производной.
   ∎
** LEARNED Лемма об оценке нормы линейного оператора
   CLOSED: [2014-11-14 Fri 11:27]
   Норма линейного оператора не больше евклидовой

   A ∈ L(m, n) ⇒ ∀ x ∈ ℝᵐ : |Ax| ≤ sqrt(∑ aᵢⱼ²)·|x|

   ▷
   Расписываем |Ax|² в сумму, херачим неравенство КБШ и все ок.
   ∎
** LEARNED Дифференцирование композиции
   CLOSED: [2014-11-14 Fri 11:29]
   Так же, как дифференцируем обычную сложную функцию

   F: E ⊂ ℝᵐ → ℝⁿ, a ∈ Int(E)
   G: I ⊂ ℝⁿ → ℝˡ, F(E) ⊂ I, F(a) ∈ Int(I)
   F дифф-ма в a, G дифф-ма в F(a)
   Тогда G ∘ F: E → ℝˡ - дифф-ма в a, причем:
   (G ∘ F)'(a) = G'(F(a)) · F'(a)

   ▷
   Расписываем определения производной, подставляем одно в другое, преобразовываем,
   в конце получаем какую-то длинную херь, доказываем что она бесконечно мала используя
   лемму об оценке нормы оператора, и значит получили определение производной для композиции.
   ∎
** LEARNED Дифференцирование "произведений"
   CLOSED: [2014-11-14 Fri 11:30]
   Аналогично тому, как дифференцировали произведение обычных функций

   F, G: E ⊂ ℝᵐ → ℝⁿ, λ: E → ℝ, a ∈ Int(E), все в a дифференцируемо.
   Тогда:
     1) (λ · F)'(a)h = (λ'(a)h) · F(a) + λ(a) · F'(a)h
     2) (<F, G>)'(a)h = <F'(a)h, G(a)> + <F(a), G'(a)h>

   ▷
   Сначала доказываем для 2 обычных функций (по определению + отсекаем беск. малые)
   потом 1) подставляем для F = (f₁..fᵣ) 2) расписываем скалярное произведение в суммы
** LEARNED Теорема Лагранжа для векторнозначных функций
   CLOSED: [2014-11-14 Fri 11:31]
   Где-то посередине на отрезке есть точка С, такая, что модуль разности на концах не превышает
   значения производной в этой точке на длину отрезка

   F: [a, b] → ℝ, F - непр. на [a, b], F - дифф-ма на (a, b)
   Тогда ∃ c ∈ (a, b) : |F(b) - F(a)| ≤ |F'(c)|(b - a)

   ▷
   Берем φ(t) = <F(b) - F(a), F(t) - F(a)>, делаем теорему Лагранжа для нее, в конце делаем КБШ.
   ∎
** LEARNED Экстремальное свойство градиента
   CLOSED: [2014-11-14 Fri 11:31]
   По градиенту можно определить направление наибыстрейшего возрастания функции.

   F: E ⊂ ℝᵐ → ℝ, a ∈ Int(E), F - дифф-ма в a.
   Тогда l = grad F(a)/|grad F(a)| - напр-е наибыстрейшего возрастания F,
   а -l – наибыстр. убывания, т. е.

   ∀ напр. h : -(δF/δl) ≤ δF/δh ≤ δF/δl

   ▷
   <grad f, h> + неравенство КБШ + тот факт, что <grad f, l> = |grad f|
   ∎
** LEARNED Независимость частных производных от порядка дифференцирования
   CLOSED: [2014-11-13 Thu 21:17]
   Если дифференцировать по разным переменным в разном порядке, получится одно и то же

   fᵤᵥ''(a) = fᵥᵤ''(a)

   ▷
   Берем выражение W = (f(x, y) - f(x₀, y) - f(x, y₀) - f(x₀, y₀))/δx̣δy,
   полагаем φ(x) = f(x, y) - f(x, y₀), ψ(y) = f(x, y) - f(x₀, y),
   переписываем W через φ и ψ, в обоих случаях 2 раза делаем Лагранжа, потом переходим к пределу и радуемся.
   ∎
** LEARNED Полиномиальная формула
   CLOSED: [2015-04-23 Thu 22:19]
   Сумма в степени мультииндекса

   (a₁ + a₂ + ... + aᵣ)ᵏ = ∑ (k!/i!) aⁱ, i: |i| = k
** LEARNED Лемма о дифференцировании "сдвига"
   CLOSED: [2014-11-14 Fri 11:37]
   k-ая производная функции "сдвига" от точки a по функции F в направлении h равна
   какой-то поеботе, похожей на полиномиальную формулу мультииндекса

   f: E ⊂ ℝᵐ → ℝ, a ∈ Int(E), B(a, ρ) ⊂ E, зафиксируем h < ρ.
   φ: [-1, 1] → ℝ, φ(t) = f(a + th).
   Тогда φ⁽ᵏ⁾(0) = ∑ (k!/i!) · hᵏ · f⁽ⁱ⁾(a)

   ▷
   Делаем первую производную, вторую... получаем k сумм спереди, вспоминаем, что это ровно то, что нужно
   ∎
** LEARNED Многомерная формула Тейлора (с остатком в форме Лагранжа и Пеано)
   CLOSED: [2014-11-14 Fri 11:38]
   То же самое, что в определениях, только вот остаток в форме Пеано: o(|x-a|ʳ)

   ▷
   Перейдем к сдвигу (x = a + h), разложим сдвиг от 1 по обычному Тейлору в 0,
   подставим в разложение выражения из леммы
   ∎
** LEARNED Теорема о пространстве линейных отображений
   CLOSED: [2014-11-14 Fri 11:39]
   В пространстве линейных отображений сущесвует норма. Кроме того,
   норма композиции не превышает произведения норм

   ∀ A ∈ L(X, Y), B ∈ L(Y, Z) : ∥B ∘ A∥ ≤ ∥B∥·∥A∥

   ▷
   1) Свойства нормы доказываются как-то очевидно, надо лишь пошафлить определение
   2) Про композицию - берем |BAx|, шафлим его, отделяем от него нормы операторов по очереди
   ∎
** LEARNED Лемма об условиях, эквивалентных непрерывности линейного оператора
   CLOSED: [2014-11-14 Fri 11:40]
   A ∈ L(X, Y) - лин. оператор
   Эквивалентно:
   1) A - ограничен (∥A∥ < ∞)
   2) A непрерывен в нуле
   3) А непрерывен всюду
   4) А равномерно непрерывен всюду

   ▷
   4 ⇒ 3 ⇒ 2 по определению
   2 ⇒ 1: берем определение непрерывности, выводим, что ∥A∥ ≤ 1/δ,
   потом берем другой x ≤ 1 и выводим что |Ax| ≤ 1/δ
   1 ⇒ 4: в определении равн. непр-ти берем δ = ε/∥A∥
   ∎
** LEARNED Теорема Лагранжа для отображений
   CLOSED: [2014-11-14 Fri 11:41]
   Все та же теорема Лагранжа, только с нормой Л. О.

   F: E ⊂ ℝᵐ → ℝⁿ, E - открыто, B(a, ρ) ⊂ E, F диф-ма на B(a, ρ), x ∈ B(a, ρ)
   Тогда ∃ с ∈ (a, x) : |F(x) - F(a)| ≤ ∥F'(c)∥̧·|x - a|

   ▷
   Берем сдвиг вдоль (a, x) - векторнознач. функцию, применяем теорему Лагранжа для нее, подставляем.
   ∎
** LEARNED Теорема об обратимости линейного отображения, близкого к обратимому
   CLOSED: [2014-11-14 Fri 13:36]
   Говно с минус единичками

   Ωᵣ - мн-во обратимых линейных операторов (A: ℝʳ → ℝʳ)
   Ωᵣ - открытое множество в Lᵣᵣ, а точнее:
   L ∈ Ωᵣ, M ∈ Lᵣᵣ : ∥M - L∥ < 1 / ∥L⁻¹∥. ТОГДА:
     1) M ∈ Ωᵣ
     2) ∥M⁻¹∥ ≤ 1 / (∥L⁻¹∥⁻¹ - ∥M - L∥)
     3) ∥M⁻¹ - L⁻¹∥ ≤ (∥L⁻¹∥ / (∥L⁻¹∥⁻¹ - ∥M - L∥)) · ∥M - L∥

   ▷
   Сначала доказываем лемму о том, что оператор, оцениваемый снизу константой, обратим,
   и его обратный ограничен. Потом как-то там все шафлим, короче пиздец.
   ∎
** LEARNED Теорема о непрерывно дифференцируемых отображениях
   CLOSED: [2014-11-14 Fri 11:44]
   То, что функция гладкая, это то же самое, что ее производная непрерывна (ЛОЛ)

   F: E ⊂ ℝᵘ → ℝᵛ, F - дифф-ма на E, F': E → Lᵤᵥ
   Эквивалентно:
     1) F ∈ C¹(E)
     2) F' непрерывно

   ▷
   1 -> 2: Устанавливаем большой ε. Оцениваем ∥F(x) - F(x₀)∥ сверху корнем суммы квадратов.
   Сумма состоит из разностей частных производных, которые мы оцениваем маленьким кусочком ε,
   пользуясь их непрерывностью. Берем самую маленькую дельту из оценок частных производных и
   подставляем ее в большое определение непрерывности.
   2 -> 1: Домножаем (F(x) - F(x₀)) на h = (0, 0.. 1 ..0), таким образом выделяем конкретную разность
   частных производных и получаем для нее ту же оценку.
   ∎
** LEARNED Лемма об оценке квадратичной формы и об эквивалентных нормах
   CLOSED: [2015-04-23 Thu 22:19]
   Всякая положительно опр. квадратная форма не больше аргумента в квадрате с какой-то константой

   Если Q - положительно определенная кв. форма, то
   1) ∃ C : ∀ x : Q(x) ≥ C · |h|²
   2) ∃ c₁, c₂ > 0 : ∀ x: c₁|x| ≤ ∥x∥ ≤ c₂|x|      (ЧТО ТАКОЕ p??)

   ▷
   1) Берем C как min Q(h) {|h| = 1} - он существует, т. к. сфера - компакт
   2) Берем с₁ и c₂ как min и max p(x) на {|x| = 1}
   ∎
** LEARNED Теорема Ферма. Необходимое условие экстремума. Теорема Ролля
   CLOSED: [2014-11-14 Fri 11:47]
   Ферма: В локальном экстремуме производная по любому направлению равна нулю

   f: E ⊂ ℝᵐ → ℝ, x₀ ∈ Int(E), x₀ - лок. экстремум. Тогда:
   ∀ l ∈ ℝᵐ, |l| = 1 : δf/δl (x₀) = 0

   НУЭ: В экстремуме производная равна нулю
   f'(x₀) = 0

   Ролль: Если по краям какой-то сферы функция принимает одно и то же значение,
   то внутри нее точно есть экстремум

   f: E ⊂ ℝᵐ → ℝ, B(x₀, r) ⊂ E - закрытый шар
   Если ∀ x ∈ S(x₀, r) : f(x) = const, то
   ∃ a ∈ B(x₀, r) : f'(a) = 0

   ▷
   1) Берем прямую вдоль направления, сужаем функцию на нее, получаем обычную функцию,
      для которой по обычной теореме Ферма производная = 0 ⇔ произв. по направлению = 0
   2) В силу произвольности направления вся производная = 0
   3) Если на всем шаре функция постоянна - очевидно, иначе по Th. Вейерштрасса она имеет min/max внутри него
   ∎
** LEARNED Достаточное условие экстремума
   CLOSED: [2014-11-14 Fri 11:49]
   Как и с обычными производными, нужно прочекать точку перегиба, для чего мы берем вторую производную.

   f: E ⊂ ℝᵐ → ℝ, B(x₀, r) ⊂ E, f ∈ C²(B), grad f(x₀) = 0
   Обозначим d²f(x₀, h) как Q(h). Тогда:
     1) если Q полож. определена, тогда x₀ - строгий минимум
     2) если Q отриц. определена, тогда x₀ - строгий максимум
     3) если Q незнакоопределенв, тогда x₀ - не экстремум
     4) если Q полуопределена, то нихера не понятно

   ▷
   1) Раскладываем f(x₀ + h) - f(x₀) как-то хитро по Тейлору до 2 дифференциала, выделяем квадр. форму,
      ограничиваем ее снизу по лемме, а оставшиеся суммы - по непрерывности част. производных,
      получаем что результат > 0 и это значит, что x₀ - минимум
   2) То же, только знаки меняются
   3) Берем 2 точки, где в 1 Q(h) > 0, а в другой - < 0. Проворачиваем ту же процидурку, и выходит что
      для разных точек близ x₀ результат разный.
   4) Хз, примерчик какой-то
   ∎
** LEARNED Лемма о "почти локальной инъективности"
   CLOSED: [2014-11-14 Fri 11:53]
   Функция, дифференцируемая в x₀ не слишком сильно слепляет близкие к x₀ точки

   F: O ∈ ℝᵐ → ℝⁿ, O - открыто, x₀ ∈ O, F - дифф-ма в x₀, det F'(x₀) ≠ 0.
   Тогда:
   ∃ с, δ > 0 : ∀ x ∈ O, |x - x₀| < δ : |F(x) - F(x₀)| ≥ c|x - x₀|

   ▷
   1) Для линейного отображения: |x| = |F⁻¹Fx| ~ с = 1/∥F⁻¹∥
   2) Общий случай: расписываем F(x) - F(x₀) по определению дифф-мости, оцениваем F'(x₀)
      как в 1 пункте, говорим, что α(x) достаточно маленькая и все ок.
   ∎
** LEARNED Теорема о сохранении области
   CLOSED: [2014-11-14 Fri 11:53]
   Диффеоморфизм сохраняет открытость множества

   F: O ∈ ℝᵐ → ℝⁿ, O - открыто, F - диффеоморфизм, ∀ x ∈ O: det F'(x) ≠ 0.
   Тогда F(O) открыто

   ▷
   Надо доказать, что ∀ x ∈ O F(x) - внутр. точка F(O)

** LEARNED Теорема о диффеоморфизме
   CLOSED: [2015-04-23 Thu 22:19]
   Диффеоморфизм одинаково гладкий в обе стороны и производная обратной функции равна обратной производной

   F: O ∈ ℝᵐ → ℝⁿ, O - открыто, F - обратима, F ∈ C¹(O), ∀ x ∈ O: det F'(x) ≠ 0.
   Тогда:
     1) F⁻¹ ∈ C¹(F(O))
     2) ∀ x, y = F(x) : (F⁻¹)'(y) = (F'(x))⁻¹

   ▷
   1) По лемме о сохранении области S = F⁻¹ - непрерывно (берем там какие-то подобласти и ок)
   2) Расписываем определение дифф-сти для F, потом формируем из него что-то похожее на определение
      для S и доказываем, что всякая фигня в хвосте бесконечно мала через почти локальную инъективность
   3) Делаем цепочку из непрерывных по всяким причинам отображений, которая оказывается отображением y ↣ S'(y)
   ∎
** LEARNED Лемма об оценке линейного приближения
   CLOSED: [2014-11-14 Fri 11:57]
   F ∈ C¹(O, ℝᵐ), x₀ ∈ O. Тогда:
   |F(x) - F(x₀) - F'(x₀)(x - x₀)| ≤ C|x - x₀|,
   где C = sup ∥F'(z) - F'(x₀)∥, z ∈ [x₀, x]

   ▷
   Берем функцию T(x) = F(x) - F'(x₀), подставляем ее в Th. Лагранжа для отображений
   ∎
** LEARNED Теорема о локальной обратимости
   CLOSED: [2014-11-14 Fri 11:57]
   Всякая гладкая функция хоть чуть-чуть, да диффеоморфизм

   F ∈ C¹(O, ℝᵐ), x₀ ∈ O, det F'(x₀) ≠ 0. Тогда:
   Тогда ∃ V(x₀) : F|ᵥ₍ₓ₀₎ - диффеоморфизм.

   ▷
   Так как det F' непрерывен вместе с F' и всегда можно найти такую окрестность x₀,
   где он не 0, нужно доказать, что F на такой окрестности обратимо.
   Доказываем, что |F'(x₀)h| ≤ c|h|, берем такую окрестность, что в ней производная убегает от значения
   в x₀ не более чем на c/4 и мучаем выражение |F(x) - F(y)|, где x, y  - из нашей окрестности.
   Расхреначиваем его на 3 модуля, один - из леммы о лин. приближении, второй - из условия на окрестность,
   третий - |F'(x₀)h|. Оцениваем их по-всякому, приходим к тому, что все выражение ≥ c/4|h|,
   что ПОЧЕМУ-ТО указывает на обратимость функции (мб потому, что разным аргументам соответсвуют разные значения?)
   ∎
** LEARNED Теорема о неявном отображении
   CLOSED: [2015-04-23 Thu 22:19]
   Для всякого нормального уравнения от x и y существует единственная непрерывная функция y

   F: E ⊂ ℝᵐ⁺ⁿ → ℝⁿ, E - открыто, F ∈ Cʳ(E, ℝᵐ), x₀ ∈ O.
   Рассмотрим (a, b) ∈ E, F(a, b) = 0
   Пусть Fᵣ'(a, b) обратима. (это производная по игрекам)
   Тогда: ∃ P(a) ∈ ℝᵐ, Q(b) ∈ ℝⁿ - открытые мн-ва, и
   ∃! φ ∈ Cʳ(P → Q):
     1) φ(a) = b
     2) ∀ x ∈ P : φ(x) ∈ Q, F(x, φ(x)) = 0
     3) φ'(a) = -(Fᵣ'(a, b))⁻¹ · Fₓ'(a, b)

   ▷
   Берем фунцию Ф(x, y) = (x, F(x, y)). Замечаем, что det Ф'(a, b) ≠ 0.
   Смотрим, как она преобразует окр-ть U(a, b), в которой она обратима.
   (U = P × Q, Ф: U → V ∈ Rᵐ⁺ⁿ), получается, что P - проекция V на Rᵐ
   Берем в этой окрестности обратную функцию Ψ = Ф⁻¹ = (x, H(x, y))
   Рассмотрим функцию φ = H(x, 0). Поподставляем ее и поймем, что она подходит по всем условиям,
   а когда мы ее подифференцируем - тоже подойдет.
   ∎
** LEARNED Теорема о задании гладкого многообразия системой уравнений
   CLOSED: [2015-04-23 Thu 22:19]
   Гладкое многообразие можно задать системой уравнений, градиенты которых
   линейно независимы

   M ⊂ ℝᵐ, 1 ≤ k ≤ m, 1 ≤ r ≤ ∞ (гладкое многообразие), точка p ∈ M
   Следующие утверждения эквивалентны:
   1) ∃ U(p) ⊂ ℝᵐ : M ∩ U(p) - простое k-мерное гладкое многообразие
   2) ∃ U'(p) ∈ ℝᵐ и ∃ f₁ .. : U'(p) →
** LEARNED Необходимое условие относительного локального экстремума
   CLOSED: [2015-04-23 Thu 22:19]
   Ф : E ⊂ ℝᵐ⁺ʳ → ℝʳ,
   f : E → ℝ  - гладкие функции

   Rg Ф'(a) = r, a - точка лок. отн. экстремума ф-ции f.
   Тогда: ∃ λ = (λ₁, λ₂ ... λᵣ) ∈ ℝʳ, такая, что:
   1) f'(a) - λФ'(a) = 0
   2) Ф(a) = 0

   ▷
   Пусть a = (aₓ, a_y)
   Так как Rg Ф'(a) = r, то Ф подходит под теорему о неявном отображении и ∃ Y: U -> V
   ∀ x ∈ U: Ф(x, Y(x)) = 0
   Заметим, что aₓ - точка локального экстремума ф-ции f(x, Y(x)), продифференцируем ее и приравняем нулю,
   то же сделаем с Ф(x, Y(x)), домножим результат дифф-я Ф на λ, вычтем одно из другого, поприравниваем скобочки нулю
   и получим требуемое условие.
   ∎
** LEARNED Свойства объема: усиленная монотонность, конечная полуаддитивность, субтрактивность
   CLOSED: [2014-11-14 Fri 12:00]
   Усиленная монотонность: если некоторый дизъюнктный набор множеств содержится
   в одном большом множестве, то объем большого множества не меньше суммарного объема
   всех маленьких множеств из набора

   μ: P → ℝ⁺, A₁..Aᵣ ∈ P - дизъюнкт. набор, ⊔Aᵢ ⊂ A ∈ P, тогда ∑ μ(Aᵢ) ≤ μ(A)

   Конечная полуаддитивность: если некое большое множество покрывается набором
   маленьких, то объем большого не больше суммарного объема маленьких

   A₁..Aᵣ, A ∈ P, A ⊂ ∪Aᵢ ⇒ μ(A) ≤ ∑μ(Aᵢ)

   Субтрактивность: объем разности двух множеств есть разность их объемов

   A ⊂ B ∈ P, μ(B) < ∞ ⇒ μ(B ﹨ A) = μ(B) - μ(A)

   ▷
   1) Возьмем дизъюнктный набор разниц между A и Аₖ. Мера А – сумма мер этих двух наборов.
   2) Волевым усилием обрежем Aᵢ так, чтобы получился дизъюнктный набор, равный A. Сумма мер обрезков ≥ 0
   3) Разница м\у В и А - это некоторый дизъюнктный набор, пошафлим этот факт - получим нужное выражение для его меры.
   ∎
** LEARNED Теорема об эквивалентности счетной аддитивности и счетной полуаддитивности
   CLOSED: [2014-11-14 Fri 12:00]
   μ : P → ℝ⁺ - объем

   Счет. аддитивность: A₁, A₂... ∈ P - счетный дизъюнкт. набор, A ∈ P, A = ⊔Aᵢ ⇒
   ⇒ μ(A) = ∑ μ(Aᵢ) (сумма ряда)

   Счет. полуаддитивность: A₁, A₂... ∈ P - счетный набор, A ∈ P, A ⊂ ∪Aᵢ ⇒
   ⇒ μ(A) ≤ ∑ μ(Aᵢ) (сумма ряда)

   Эти два свойства эквивалентны.

   ▷
   1 ⇒ 2: то же, что и в свойствах объема, только счетное.
   2 ⇒ 1: Берем дизъюнктный набор, содержащий А.
   ≤ уже доказано - полуаддитивность дана
   ≥ работает по усиленной монотонности
   ∎
** LEARNED Теорема о непрерывности снизу
   CLOSED: [2015-04-23 Thu 22:22]
   Если объем на алгебре является мерой, то он непрерывен снизу, и наоборот

   μ : ℵ → ℝ⁺. Эквивалентно:
   1) μ - мера
   2) μ - непрерывен снизу, т. е.
      A₁ ⊂ A₂ ⊂ ... ∈ ℵ, A ∈ ℵ
      A = ∪ Aᵢ ⇒ μ(A) = lim μ(Aᵢ), i → ∞

   ▷
   1 ⇒ 2: Берем "колечки" от Aᵢ - дизъюнктный набор равный A Мера А - предел
   их частичных сумм, а значит - предел Aᵢ
   2 ⇒ 1: Делаем то же самое, только наоборот: в этом случае пользуемся конечной аддитивностью.
   ∎
** LEARNED Формулировка теоремы о лебеговском продолжении меры
   CLOSED: [2015-04-24 Fri 00:11]
   μ₀ - σ-конечный объем на P₀. Тогда:
   ∃ ℵ ⊃ P₀, ℵ - σ-алгебра, μ - мера на ℵ, такая, что:
     1) μ - продолжение μ₀ с P₀ на ℵ
     2) μ - полная мера
     3) μ - минимальное продолжение, т.е.
        μ' - мера на σ-алгебре ℵ' - продолжение μ₀; μ' - полная ⇒ ℵ ⊂ ℵ' и μ'|ₐ = μ
     4) P₁ - полукольцо, P₀ ⊂ P₁ ⊂ ℵ, μ₁ - продолж. μ₀ на P₁ ⇒ сужение μ на P₁ = μ₁
     5) ∀ A ∈ ℵ : μ(A) = inf {∑ μ(Pᵢ), A ⊂ ∪Pᵢ, Pᵢ ∈ P₀}
** LEARNED Счетная аддитивность классического объема
   CLOSED: [2014-11-14 Fri 12:05]
   Классический объем счетно аддитивен (wow!), то есть является мерою (причем σ-конечной!).

   μ: Pᵐ → ℝ⁺, Pᵐ - кольцо ячеек в ℝᵐ (параллелепипеды [a, b))
   μ[a, b) = ∏(bᵢ - aᵢ) - классический объем.
   Пусть A₁, A₂... ∈ Pᵐ - дизъюнкт. счетный набор параллелепипедов, A = ⊔Aᵢ ∈ Pᵐ
   ⇒ μ(A) = ∑ μ(Aᵢ)

   ▷
   σ-конечность очевидна - просто будем брать большие-пребольшие ячейки
   Докажем счетную полуаддитивность: очень нагло наберем различных закрытых/открытых
   параллелепипедов, скажем, что их меры отличаются на какие-то там эпсилоны,
   Так же внаглую напишем счетное неравенство для левых параллелепипедов, потом добавим эпсилоны
   и перейдем к ячейкам
   ∎

** LEARNED Лемма о построении открыого множества с помощью ячеек
   CLOSED: [2015-04-24 Fri 01:34]
   Открытое множество можно составить из счетного числа параллелепипедов

   1) A - открытое, ⇒ ∃ дизъюнкт. набор ячеек P₁, P₂... : A = ⊔Pᵢ
   2) Можно считать, что каждая ячейка - куб с рац. координатами.
   3) Е - измеримое, λE = 0, тогда ∀ ε > 0 ∃ Pᵢ - кубы : E ⊂ U Pᵢ , ∑λPᵢ < ε

   ▷
   Хуй знает, как это работает.
   1) Берем для каждого икса в А ячейку с рац. координатами такую, что она поместится в А.
      Координаты - рациональные, поэтому число ячеек счетно. Нумеруем их и обрезаем так, чтоб они стали
      дизъюнктными.
   2) ПОЧЕМУ-ТО берем двоично-рациональные ячейки, и все ок.
   3) Берем набор маленьких произвольных ячеек, расширяем их до двоично-рациональных чуть-чуть и они
      все равно остаются маленькими и их можно порезать на кубы
   ∎
** LEARNED Пример неизмеримого по Лебегу множества
   CLOSED: [2014-11-14 Fri 12:05]
   Возьмем отношение эквивалентности на [0, 1]: x ~ y, если x - y ∈ Q.
   Выберем представителя из каждого класса эквивалентности - множество представителей неизмеримо
** LEARNED Регулярность меры Лебега
   CLOSED: [2015-04-22 Wed 15:11]
   Всякое измеримое множество можно окружить 2-мя множествами
   изнутри и снаружи так, что получившаяся проскойка будет сколь угодно маленькой.

   ∀ A ∈ Mᵐ: sup {λ(X) | X ∈ Mᵐ - замкнутое, X ⊂ A} = λ(A) = inf {λ(G) | G ∈  Mᵐ - открытое, A ⊂ G}

   ∀ A ∈ Mᵐ:
   1) ∀ ε > 0 ∃ G ∈ Mᵐ - открытое, A ⊂ G : λ(G ∖ A) < ε
   2) ∀ ε > 0 ∃ X ∈ Mᵐ - замкнутое, X ⊂ A : λ(A ∖ X) < ε

   ▷ ХЗ ∎
** LEARNED Лемма о "прообразе меры"
   CLOSED: [2015-04-24 Fri 00:15]
   Если нам дана одна алгебра с мерой, а другая без, и между ними есть биекция,
   то насадив меру для 1-ой алгебры на биекцию, получим меру для второй

   Пусть есть (X', ℵ', μ) - алгебра над X' с мерой,
   (X, ℵ) - алгебра над X,
   T : X -> X' - биекция, A ∈ ℵ ⇒ T(A) ∈ ℵ', T(ø) = ø, T(X) = X'

   Тогда ν(A) = μ(T(A)) - мера в ℵ.

   ▷
   Так как T - биекция, она сохраняет дизъюнктность множеств, и счетная аддитивность
   новой меры тривиально доказывается
   ∎

** LEARNED Лемма о сохранении измеримости при непрерывном отображении
   CLOSED: [2014-11-28 Fri 03:24]
   Воздействуя непрерывным отображением, сохраняющим ноль, на множество,
   мы не повлияем на его измеримость.

   Пусть T ∈ C(ℝᵐ → ℝᵐ), ∀ A ∈ Mᵐ , λ(A) = 0 : λ(T(A)) = 0
   Тогда ∀ A ∈ Mᵐ : T(A) ∈ Mᵐ

   ▷
   Если А ограничено, то оно делится на дизъюнктный набор компактов и что-то меры 0.
   Непрерывное отображение сохраняет компакт => в результате множество тоже будет состоять
   из компактов и нулевого - будет измеримо.
   Если неограничено - вступает в силу сигма-конечность.
   ∎
** LEARNED Инвариантность меры Лебега относительно сдвигов
   CLOSED: [2014-11-28 Fri 03:24]
   Если мы подвинем множество, его мера не изменится.

   Пусть x₀ ∈ ℝᵐ, T : ℝᵐ → ℝᵐ , T(x) = x + x₀
   Тогда ∀ A ∈ Mᵐ : λ(A) = λ(T(A))

   ▷
   Разобьем все на ячейки - с ними сдвиг точно ниче не делает.
   Сдвиг непрерывен, и докажем сохранение нуля по 5 пункту Лебеговского продолжения.
   Тогда вся измеримость сохранится и результирующая мера будет той же.
   ∎
** LEARNED Лемма о покрытии множества нулевой меры шарами
   CLOSED: [2014-11-28 Fri 03:24]
   Множество нулевой меры можно покрыть шарами, сколь угодно близко приблизив покрытие к нулю.

   ∀ C ∈ Mᵐ, λC = 0 ∀ ε > 0 : ∃ B₁, B₂... - посл-ть шаров, такая, что
   C ⊂ ∪Bᵢ, ∑ λ(Bᵢ) < ε

   ▷
   Покроем множество нулевой меры кубическими ячейками (по лемме), потом заключим
   каждую ячейку в шар и докажем, что там не сильно прибавилось
   ∎
** LEARNED Инвариантность меры Лебега при ортогональном преобразовании
   CLOSED: [2014-11-28 Fri 03:24]
   При всяком ортогональном преобразовании (перенос, поворот) мера Лебега не меняется.

   Пусть T: ℝᵐ → ℝᵐ - ортогональное преобразование
   Тогда ∀ A ∈ Mᵐ: T(A) ∈ Mᵐ, λA = λT(A)

   ▷
   Делаем примерно то же самое, что и со сдвигом, только пользуемся
   шарами, а не ячейками, и в конце внаглую говорим, что мы знаем свойство
   инвариантных относительно сдвига мер.
   ∎
** LEARNED Теорема о сохранении измеримости при гладком отображении
   CLOSED: [2014-11-28 Fri 03:24]
   Гладкое отображение сохраняет измеримость множества

   Пусть F ∈ C¹(O ⊂ ℝᵐ → ℝᵐ)
   Тогда ∀ A ∈ Mᵐ, A ⊂ O : F(A) ∈ Mᵐ

   ▷
   Докажем сохранение нуля. Покроем нулевое множество кубами, и покажем,
   что благодаря теореме Лагранжа эти кубы не сильно растянутся, и смогут быть ограничены
   эпсилоном.
   ∎
** LEARNED Лемма "о структуре компактного оператора"
   CLOSED: [2015-04-24 Fri 00:16]
   Компактный линейный оператор можно задать 2 базисами и набором коэффициентиков
   через ебаную сумму со скалярными произведениями.

   Пусть V : ℝᵐ → ℝᵐ - невырожденный линейный оператор.
   Тогда ∃ hᵢ, gᵢ - базисы в ℝᵐ и sᵢ - набор коэффициентов, такие, что
   ∀ x ∈ ℝᵐ : V(x) = ∑ sᵢ<x, gᵢ>hᵢ,
   причем |det V| = s₁ · s₂ · ... · sm

   ▷
   Линааал))) Делаем вид, что знаем его
   Берем W = VᵗV, берем его собственные числа и базис из собственных векторов.
   С помощью линальной магии строим еще один набор векторов, доказываем что он базис,
   потом подставляем разложение икса по базису в выражение V(x), шафлим и вуаля!
   ∎
** LEARNED Теорема о преобразовании меры Лебега при линейном отображении
   CLOSED: [2015-04-22 Wed 12:00]
   Линейное отображение сохраняет измеримость и домножает меру на свой
   определитель.

   Пусть V : ℝᵐ → ℝᵐ - линейное отобр-е. Тогда:
   ∀ A ∈ Mᵐ : V(A) ∈ Mᵐ, λ(V(A)) = |det V| · λ(A) (считаем, что 0 · ∞ = 0)

   ▷
   Если оператор вырожден, то все множества что он выплевывает будут нулевыми.
   Если нет, то т. к. линейность => гладкость - измеримость сохраняется.
   Вспоминаем голословную инвариантность относительно сдвигов, считаем на кубике,
   получаем нужную константу.
   ∎
** LEARNED Теорема об измеримости пределов и супремумов
   CLOSED: [2015-04-23 Thu 22:38]
   Пределы (верхний/нижний) и супремумы/инфиумы последовательности измеримых функций измеримы.

   fₙ - посл-ть измеримых функций. Тогда:
   1) sup{fₙ}, inf{fₙ} - измеримы
   2) ulim fₙ, llim fₙ - измеримы
   3) если lim fₙ = f - существует, то f - измерима

   ▷
   из 2 сразу следует 3, доказать надо первые 2:
   1) Возьмем Лебегово множество для супремума по > a - это пересечение таких
      же множеств для всех fₙ - измеримо. Для инфиума так же.
   2) Возьмем функцию - супремум остатка последовательности, тогда верхний предел - это
      инфиум этой функции, а значит - измерим по п. 1
   ∎
** LEARNED Характеризация измеримых функций с помощью ступенчатых. Следствия.
   CLOSED: [2015-04-24 Fri 00:18]
   Всякую неотриц. измеримую функцию можно представить как предел возрастающей
   последовательности ступенчатых функций.

   Пусть f ≥ 0 - измерима на X, тогда ∃ gₙ - последовательность ступ. функций,
   такая, что ∀ x ∈ X:
   1) 0 ≤ gₙ ≤ f
   2) ∀ k: gₖ ≤ gₖ₊₁
   3) lim gₙ = f

   Следствие 1: это работает и для знакопеременных функций. только |gₙ| ≤ |f|
   Следствие 2: это работает для произведения измеримых функций.

   ▷
   Возьмем в общем ступенчатую функцию hₙ, которая прилегает снизу к f, и чем больше n,
   тем сильнее прилегает (кусочки разбиения сокращаются). Тогда для нее будут выполняться
   все условия кроме монотонности по n; исправим это, взяв gₙ = max {h₁ .. hₙ}

   Следствие 1: берем + и - срезки, применяем для них
   Следствие 2: берем произведение ступенчатых функций
   ∎
** LEARNED Измеримость монотонной функции
   CLOSED: [2015-06-22 Mon 15:36]
   Видимо, всякая монотонная функция измерима!

** LEARNED Теорема Лебега о сходимости почти везде и по мере
   CLOSED: [2015-04-24 Fri 00:18]
   Если последовательность функций сходится почти везде в пространстве **конечной** меры, то она сходится по мере.

   (X, ℵ, μ) - пространство конечной меры: μX < +∞
   fₙ → f почти везде на X. Тогда fₙ ⇒ f по мере

   ▷
   Достроим функции на множестве нулевой меры так, чтоб они сходились и на ней.
   1. Сначала докажем для fₙ ≥ 0, f = 0, fₙ - монотонно убывает по n.
   Для всякого эпсилона лебегово множество fₙ большего эпсилона включает в себя
   такое же следующее - это счетный набор вложенных множеств, и его пересечение = ∅.
   По непрерывности меры сверху их меры стремятся к нулю.
   2. Перейдем к произвольным функциям: возьмем функцию gₙ = sup |fₖ - f| ∀ k ≥ n
   Применим 1 пункт к ней и все ок.
   ∎
** LEARNED Теорема Рисса о сходимости по мере и почти везде
   CLOSED: [2015-04-24 Fri 00:19]
   Если fₙ сходится к f по мере, то *некоторая подпоследовательность* сходится к fₙ почти везде.

   (X, ℵ, μ), fₙ ⇒ f по μ. Тогда ∃ nₖ: fₙₖ → f почти везде.

   ▷
   Возьмем nₖ, которая с каждым шагом все сильнее (1/2ᵏ) уменьшает меру разницы.
   Возьмем хитрую последовательность вложенных множеств Eₖ, похожих на определение
   сходимости по мере. По непрерывности сверху и хитрому определению nₖ их пересечение будет
   иметь меру 0, а для всех иксов не из пересечения выясняется, что на них при больших
   k нет границы сближения с f.
   ∎
** LEARNED Простейшие свойства интеграла Лебега
   CLOSED: [2015-06-22 Mon 15:36]
   Интеграл Лебега монотонен, сохраняет 0 и 1, сохраняет нулевую меру,
   позволяет выносить константу, подчиняется "неравенству треугольника" с модулями,
   монотонен отн. константы и суммируемая функция должна быть конечной почти всюду.

   1) f ≤ g - сумм. ф-ции ⇒ ∫f ≤ ∫g      - монотонность
   2) ₓ∫1dμ = μX, ∫0dμ = 0               - сохранение 0 и 1
   3) ∀ E: μE = 0: ₑ∫f = 0               - сохранение мн-ва нулевой меры
   4) ∀ α ≥ 0: ∫αf = α∫f, ∫(-f) = -∫f    - вынесение константы за интеграл
   5) |∫f| ≤ ∫|f|                        - неравенство треугольника
   6) a ≤ f ≤ b: a · μX ≤ ₓ∫f ≤ b · μX   - монотонность отн. константы
   7) f - сумм ⇒ f - конечна п. в.       - требование о конечности почти везде

   ▷
   Все доказывается тривиально подъемом от ступенчатых функций или банальной ссылкой
   на прошлые свойства, кроме 6го - там нужно брать множества, на которых f > n, объединять
   их и смотреть че выходит.
   ∎
** LEARNED Счетная аддитивность интеграла (по множеству)
   CLOSED: [2015-04-23 Thu 22:43]
   Интеграл Лебега счетно аддитивен по множеству)))

   (X, ℵ, μ), ⊔ Aₖ = A ⊂ X, f - сумм. на A.
   Тогда ₐ∫fdμ = ∑ ₐₖ∫fdμ

   ▷
   Сначала доказываем ≤ - там просто переходим к ступенчатой функции,
   для которой счетная аддитивность верна (легко доказать) и в неравенстве переходим
   к супремуму
   Потом ≥ - начинаем с 2 множеств, берем 2 ступ. функции на них, сумма их интегралов меньше
   интеграла f - переходим к супремуму, потом по индукции доказываем справедливость для
   счетного набора.
   ∎
** LEARNED Теорема Леви о предельном переходе под знаком интеграла
   CLOSED: [2015-04-24 Fri 00:22]
   Под интегралом Лебега можно делать предельный переход, если последовательность функций
   положительна и монотонно возрастающая.

   f ≥ 0 - изм., ∀ x ∀ n: 0 ≤ fₙ(x) ≤ fₙ₊₁(x) ≤ f(x)
   fₙ → f п. в.
   Тогда lim ∫fₙdμ = ∫fdμ

   ▷
   ≤ - очевидно, по монотонности интеграла
   ≥ - какая-то ебаная магия, берем ступенчатую функцию для f, прихерачиваем к ней константу,
   разбиваем пространство на хитрые множества зависящие от n, получаем чудо-неравенство в котором
   можно сделать предельный переход и получить ровно то, что надо (только к супремуму надо перейти)
   ∎

** LEARNED Линейность интеграла
   CLOSED: [2015-04-23 Thu 23:02]
   Интеграл Лебега линеен))

   f, g ≥ 0: ∫(f + g) dμ = ∫f + ∫g

   ▷
   Берем последовательности ступ. функций, стремящихся к f и g, делаем сумму для
   их интегралов и делаем предельный переход
   ∎

** LEARNED Простейшие свойства интеграла векторного поля по кусочно-гладкому пути
   CLOSED: [2015-06-22 Mon 15:36]
   Такой интеграл линеен, аддитивен, в нем можно сделать замену параметра,
   можно сделать объединение носителей путей, можно пойти по пути назад и сменить знак
   результата, а можно его оценить сверху максимумом значения поля на длину пути.

   1) I(αV + βU, γ) = αI(V, γ) + βI(U, γ)                              - линейность
   2) γ : [a, b] → ℝᵐ, c ∈ (a, b), γ₀ = γ\[a, c], γ₁ = γ\[c, b]        - аддитивность
      ⇒ I(V, γ) = I(V, γ₀) + I(V, γ₁)
   3) φ: [p, q] → [a, b], φ(p) = a, φ(q) = b                           - замена параметра не влияет на результат
      γ' = γ ∘ φ ⇒ I(V, γ) = I(V, γ')
   4) γ₀ : [a, b] → ℝᵐ, γ₁ : [p, q] → ℝᵐ                               - объединение носителей
      γ : [a, b + q - p] → ℝᵐ
      γ(t) = { γ₀(t), t ∈ [a, b], γ₁(t - b + p), t ∈ [b, b + q - p] }
      Тогда I(V, γ) = I(V, γ₀) + I(V, γ₁)
   5) γ₋(t) = γ(b - t + a)                                             - развернутый путь с отрицательным знаком
      ⇒ I(V, γ₋) = -I(V, γ)
   6) l(γ) - длина пути                                                - оценка сверху длиной пути на максимум
      |I(V, γ)| ≤ max |V(x)| · l(γ), x ∈ γ[a, b]

   ▷
   Все очень тривиально доказывается
   ∎

** LEARNED Обобщенная формула Ньютона-Лейбница
   CLOSED: [2015-04-23 Thu 23:02]
   Интеграл потенциального поля равен разности потенциалов на концах пути.

   V - потенц. векторное поле, φ - потенциал (V = grad φ)
   γ : [a, b] -> ℝᵐ - кусочно-гладкий путь.

   Тогда I(V, γ) = φ(γ(b)) - φ(γ(a))

   ▷
   Берем композицию потенциала и пути, выясняем, что ее производная - как раз интегральное
   выражение по определению. Подставляем и применяем обычную формулу Ньютона-Лейбница.
   ∎
** LEARNED Характеризация векторных полей в терминах интегралов
   CLOSED: [2015-04-24 Fri 00:26]
   В потенциальном поле интеграл не зависит от формы пути и интеграл петли = 0 - в любом порядке

   1) Поле потенциально
   2) Интеграл не зависит от формы пути
   3) Интеграл петли равен 0

   Это все эквивалентно
   ▷
   1 ⇒ 2 по формуле Ньютона-Лейбница
   2 ⇔ 3 - очевидно
   2 ⇒ 1 - возьмем точку с нулевым потенциалом x₀ и определим потенциал для каждой другой
   точки как интеграл поля по пути от x₀ до нее
   ∎
** LEARNED Лемма о дифференцировании интеграла по параметру.
   CLOSED: [2015-04-23 Thu 23:03]
   Если мы дифференцируем некоторый интеграл с параметром по нему, то
   результатом будет тот же интеграл, только с частной производной по параметру внутри.

   ▷
   Распишем производную по параметру по определению производной,
   применив теорему Лагранжа получим какой-то предел с интегралами,
   поточечно сходящийся к тому, что мы хотим. Докажем равномерную сходимость через
   равномерную непрерывность частной производной (она есть по Кантору)
   ∎
** LEARNED Необходимое условие потенциальности поля. Лемма Пуанкаре.
   CLOSED: [2015-04-23 Thu 23:05]
   Если поле потенциально, то тогда во всякой частной производной поля индексы
   вверху и внизу можно поменять местами. И наоборот, если поле задано на выпуклой области.

   1) ∀ i, j : ∂Vᵢ/∂xⱼ = ∂Vⱼ/∂xᵢ, X - выпуклое мн-во ⇒ V - потенциально на X
   2) V - потенциально ⇒ ∀ i, j : ∂Vᵢ/∂xⱼ = ∂Vⱼ/∂xᵢ

   ▷
   Необходимость - тривиально, перейдем ко 2 производным потенциала.
   Достаточность - сделаем как бы потенциал из нулевой точки по прямым путям.
   Распишем интеграл по прямому пути, продифференцируем по xₖ, свопнем индексы, пошафлим -
   убедимся, что наш потенциал хороший.
   ∎
** LEARNED Лемма о гусенице
   CLOSED: [2015-04-23 Thu 23:05]
   Всякий непрерывный путь можно покрыть сколь угодно тоненькой гусеницей

   γ : [a, b] → ℝᵐ - непрерывный путь.
   ∀ ε > 0 : ∃ Bₙ - набор шаров : γ([a, b]) ⊂ ∪Bₙ, λ(∪Bₙ) < ε

   ▷
   Берем конечное подпокрытие [a, b] интервалами, в каждом берем по уникальной точке,
   замечаем точки пересечения, натягиваем шарик между ними.
   ∎
** LEARNED Лемма о равенстве интегралов по похожим путям
   CLOSED: [2015-04-23 Thu 23:07]
   Интегралы по похожим путям равны
   γ₁, γ₂ : [a, b] → ℝᵐ - похожие пути
   I(V, γ₁) = I(V, γ₂)

   ▷
   Берем общую гусеницу и подгоняем потенциалы в каждом шарике гусеницы друг под друга.
   Цепочные суммы потенциалов для обоих путей равны.
   ∎
** LEARNED Лемма о похожести путей, близких к данному
   CLOSED: [2015-04-23 Thu 23:07]
   Близкие пути похожи.

   γ : [a, b] → O ⊂ ℝᵐ - непрерывный путь
   Тогда ∃ δ > 0 : ∀ γ₁, γ₂ : [a. b] → O, ∀ t ∈ [a, b] :
      |γ₁(t) - γ₂(t)| < δ, |γ₂(t) - γ(t)| < δ : γ₁ и γ₂ похожи

   ▷
   Берем гусеницу данного пути. Каждую точку каждого отрезка разбиения покрываем своим
   маленьким шариком. Если близкие пути лежат в этих маленьких шариках, то они обслуживаются той же гусеницей.
   ∎
** LEARNED Равенство интегралов по гомотопным путям.
   CLOSED: [2015-04-23 Thu 23:07]
   Интегралы по гомотопным путям равны.

   V : O ⊂ ℝᵐ → ℝᵐ - век. поле,
   γ₁, γ₂ : [a, b] → O - непрерывные гомотопные пути в О
   Тогда I(V, γ₁) = I(V, γ₂)

   ▷
   Чтобы доказать, что функция интеграла по промежуточному пути постоянна, докажем, что она локально постоянна.
   Воспользуемся равномерной непрерывностью гомотопии - возьмем из нее все нужные буквы для леммы о близких путях
   По лемме о близких путях постоянность докажется.
   ∎
** LEARNED Почему резиночку нельзя снять с гвоздика?
   CLOSED: [2015-06-22 Mon 15:36]
   Видимо, это про то, что локально потенциальное поле в односвязной области потенциально.

   ▷
   Всякая петля гомотопна точечному пути, а точечный путь в локально-потенц. поле делает нулевой интеграл.
   ∎

   А резиночку-то почему нельзя? Видимо, потому что иначе поле было бы потенциально, а так нельзя.
** LEARNED Об интегрировании положительных рядов
   CLOSED: [2015-06-22 Mon 16:40]
   Интеграл Лебега от суммы положит. функ. ряда равен сумме интегралов от функций

   Uₙ - положительные функции, измеримы, тогда
   ∫(∑Uₙ)dμ = ∑∫(Uₙ)dμ

   ▵
   Возьмем частичные суммы Uₙ, подставим вместо рядов пределы от них и получим что надо
   по теореме Леви.
   ▿
** LEARNING Об абсолютной непрерывности интеграла
   Всегда можно подобрать маленькую-маленькую область, на которой интеграл будет сколь угодно маленьким.

   (X, ℵ, μ), тогда для любой суммируемой f
   ∀ δ > 0 : ∃ ε > 0 : ∀ A ∈ ℵ, μ(A) < ε : ₐ∫|f|dμ < δ

   ▵
   Возьмем последовательность вложенных множеств типа xₙ = X(|f| > n). Она сжимается
   в множество меры 0, ведь f - суммируема. ν(e) = ₑ∫|f|dμ - мера, т. к. положительно и счетно аддитивно,
   значит - ν(xₙ) → 0 (по непрерывности сверху). Ну тут расписываем этот факт с эпсилоном,
   берем хитровыебанную δ = ε/2nₑ, шафлим и получаем что надо.
   ▿
** LEARNING Лебега о мажорированной сходимости для сходимости по мере
   Если посл. функций сходится по мере и имеет суммируемую мажоранту, то интегралы разностей сходятся.

   (X, A, μ)
   f, fₙ : X → ℝ, fₙ ⇒ f по мере μ,
   ∃ g : g - суммируемая и |fₙ| ≤ g для почти всех x, тогда
   fₙ, f суммируемые и ∫|f - fₙ| → 0

   ▵
   fₙ, а значит, f - суммируемы, так как ограничены по модулю суммируемой g.
   Рассмотрим 2 случая:
   1) μX < +∞
      Xₙ = X(|fₙ - f| > ε), по опр. сходимости по мере, μXₙ → 0
      Теперь разобьем ₓ∫|fₙ - f| = ₓₙ∫ + ₋ₓₙ∫, обе части норм оценятся сверху, ведь -Xₙ - конечна.
   2) μX = +∞
      Докажем, что есть такой конечный А, что интеграл мажоранты по X\A мал.
      Для этого возьмем A = носитель ступенчатой функции, прилегающей к g.
      Тогда X_∫ = A_∫ + (X\A)_∫ - оценивается, ведь А - конечно (по 1 пункту все ок),
      и (X\A)_∫ мало по построению.
   ▿
** LEARNING Лебега о мажорированной сходимости для сходимости почти везде
   Если посл. функций сходится почти везде и имеет суммируемую мажоранту, то интегралы разностей сходятся.

   (X, ℵ, μ), fₙ, f: X → ℝ~, fₙ → f почти везде
   ∃g, суммируемая, ∀n : |fₙ| ≤ g для почти всех x
   Тогда:
   fₙ, f - суммируемые, ∫|fₙ - f|dμ → 0

   ▵
   fₙ, f суммируемы как и в прошлой теореме.
   Возьмем hₙ - супремумы разностей модулей, hₙ ≥ hₙ₊₁
   Они также оцениваются сверху мажорантой (2g).
   Посмотрим на предел lim ∫ (2g - hₙ), пошафлим и поймем, что ∫hₙ → 0, это то что надо
   ▿
** LEARNED Теорема Фату
   CLOSED: [2015-06-23 Tue 00:08]
   Если посл-ть сходится к f почти везде, и каждый член последовательности чем-то
   сверху ограничен, то f ограничена так же.

   (X, ℵ, μ)
   fₙ → f почти везде по X, и ∃ C : ∀ n : ∫fₙdμ < C, тогда
   ∫fdμ < C

   ▵
   Возьмем gₙ - последовательность инфиумов fₙ - неубывающая последовательность,
   значит, работает теорема Леви, и мы можем перейти к пределу под интегралом и
   получить что хотим.
   ▿
** LEARNING Теорема Лебега о непрерывности интеграла по параметру
   Интеграл хорошей непрерывной функции по одному аргументу непрерывен по второму.

   (X, A, μ)
   f: X × Y → ℝ, ∀y : x ↦ f(x, y) имеет смысл, то есть сумм.
   1. f удовлетворяет Lₗₒₖ в y₀
   2. f(x, y) непрерывно в y₀ при почти всех x
   Тогда:
   I(y) = ∫f(x, y)dμ(x) непрерывно в y₀

   ▵
   Рассмотрим непрерывность по Гейне. 2 условие превращается в сходимость посл-ти
   почти везде, + мажоранта ⇒ по Th. о мажорированной сходимости посл-ть интегралов
   сходится к интегралу в y₀, что определение непрерывности по Гейне.
   ▿

** LEARNING Правило Лейбница о дифференцируемости интеграла по параметру
   Производная интеграла по параметру равна интегралу производной внутренней функции по этому параметру.

   (X, A, μ)
   f: X × Y → ℝ, Y ⊂ ℝ - промежуток

   1. x ↦ f(x, y) суммируемо
   2. f дифференцируемо по y при почти всех x
   3. f'_y удовлетворяет Lₗₒₖ в y0

   Тогда
   (∫f(x)dμ(x))'_y = ∫f'_y(x)dμ(x)

   ▵
   Рассмотрим типа-производную F(x, h) = (f(x, y₀ + h) - f(x, y₀))/h.
   Она стремится в нуле к частной производной, значит - непрерывна в 0.
   Докажем, что ее интеграл по x непрерывен в нуле (это то, что нужно, ведь ее интеграл - типа-производная I(y₀)
   Для этого надо показать Lₗₒₖ(0) для F, ну там из 3 условия легко следует.
   ▿
** LEARNING Вычисление интеграла Дирихле
   ₀∫^∞ (sinαx/x) = π/2 sgn α

   ▵
   Добавим под интеграл e⁻ˣʸ и получившееся возьмем с помощью дифференцирования по y.
   Получится π/2 - arctg(y). Докажем, что этот интеграл стремится к искомому в нуле:
   рассмотрим их разность, поделим ее на [0, t], (t, +∞) и оценим обе части, все получится.
   ▿
** LEARNING Теорема об вычислении интеграла по взвешенному образу меры
   Чтобы проинтегрировать функцию по взвешенному образу меры, нужно проинтегрировать ее по
   оригинальной мере, домножив на вес.

   (X, A, μ), (Y, B, _)
   Φ : X → Y, ν = ∫wdμ,
   f - положительная, измеримая или суммируемая на Y, тогда
   ∫fdν = ∫_Φ⁻¹ f(Φ(x))w(x)dμ

   ▵
   Продвинемся так: характерисическая → ступенчатая → полож. измеримая → суммируемая
   1) очевидно
   2) очевидно из 1
   3) представим f как предел возрастающих ступ. функций + теорема Леви
   4) сделаем это для обеих срезок
   ▿
** LEARNING Критерий плотности
   Функция является плотностью меры ν отн. μ iff ее инфиум и супремум не пускают ν далеко от μ

   (X, ℵ, μ), (Y, ℶ, _)
   X = Y, ℵ = ℶ,
   ν=∫_Φ⁻¹ wdμ, w - положительная, измеримая на X,

   w - плотность ν относительно μ тогда и только тогда, когда
   ∀ A ∈ ℵ : μA·inf w ≤ νA ≤ μA·supw

   ▵
   Необходимость очевидна, c достаточностью магия:
   разобьем множество A на кучу маленьких, где w ограничено между qᵏ и qᵏ⁻¹,
   поставим рядом неравенство из условия и неравенство для интеграла, пошафлим,
   устремим q к единице и все ок.
   ▿
** LEARNING Лемма о множествах вполне положительности заряда
   Во множестве с положительным зарядом найдется множество положительности.

   (X, A, μ), E ∈ A, μE ≥ 0
   тогда найдется G ⊂ E - множество положительности, μ(G) ≥ μ(E)

   ▵
   Введем понятие множества ε-положительности, докажем, что они есть
   для любого ε, построим набор множеств с уменьшающимся эпсилоном, который в
   пределе даст множество положительности.
   ▿
** LEARNING Теорема Радона-Никодима. Доказательство единственности.
   Если мера абсолютно непрерывна относительно другой, то между ними существует плотность (единственная!).

   (X, A, (ν,μ))
   ν абсолютно непрерывна относительно μ, тогда
   ∃! w(x) : w - сумм. отн. μ, w - плотность ν относительно μ

   ▵
   Единственность:
   Пусть есть две такие плотности f, g - докажем, что f - g почти везде 0.
   Знаем, что ∫(f - g) = 0, ну тогда легко доказать что и ∫|f - g| = 0, из чего
   следует f = g почти везде
   ▿
** LEARNING Теорема Радона-Никодима. Доказательство существования.
   ▵
   Построим множество всех функций, интегралы которых не превышают второй меры.
   Возьмем супремум этого множества (по X) и предельную функцию, интеграл которой по X равен ему.
   Докажем, что интеграл этой функции не меньше меры от противного:
   представим такое плохое (ненулевое!) A₀, построим маленький заряд, такой, что на нем он > 0,
   выделим множество положительности заряда и поподставляем его в интегралы. Там придем
   к противоречию, что супремум - не супремум.
   ▿
** LEARNING Лемма об оценке мер образов кубов из окрестности точки дифференцируемости
   Образ такого куба дифференцируемым отображением имеет меру, отличающуюся от
   меры Лебега самого куба на определенную константу.

   Φ: O ⊂ ℝᵐ → ℝⁿ, a ∈ O, Φ дифф. в точке a.
   Пусть 0 < |det Φ'(a)| < C, λₘ - мера Лебега в ℝᵐ
   Тогда ∃Uₐ : ∀ Q - куб, Q ∈ Uₐ, a ∈ Q : λₙ(Φ(Q)) ≤ c · λₘQ

   ▵
   Распишем определение дифференцируемости для Ф, пошафлим и выделим лин. оператор
   Ψ (Ф'(a)⁻¹ со сдвигом). Он сдвигает точку x очень недалеко, ну значит, и Ф раздвинул
   точки ненамного дальше - а именно, на |det Ф'(a)|.
   ▿
** LEARNING Теорема о преобразовании меры Лебега при диффеоморфизме
   Мера диффеоморфного образа равна интегралу якобиана по прообразу.

   Φ: O ⊂ ℝⁿ → ℝⁿ - диффеоморфизм,
   ∀ b ∈ Mᵐ : λ(Φ(b)) = ∫_b |det Φ'(x)|dλ

   ▵
   Пиздец какой-то, мда. Доказываем для якобиана критерий плотности,
   почему-то только правое неравенство. Доказываем его для кубов - от противного к
   противоречию с предыдущей леммой, отсюда следует верность для всех открытых множеств.
   Доказательство для не только открытых - это ебать, там че-то по регулярности
   меры выразили ее через инфиум открытых, подставили, и доказываем через какую-то
   поеботу что получилось ровно то, что нам нужно.
   ▿
** LEARNED Теорема о гладкой замене переменной в интеграле Лебега
   CLOSED: [2015-06-25 Thu 00:46]
   Когда заменяем переменные, надо подставить замену вместо вхождений и домножить на якобиан.

   Φ: O ⊂ ℝⁿ → ℝⁿ диффеоморфизм, O' = Φ(O), тогда
   f - положительная, измеримая на O' или суммируемая на O'
   ∫_O' fdλ = ∫_O f∘Φ(x)|det Φ'(x)|dλ

   ▵
   Прошлая теорема + теорема о взвешенном образе меры
   ▿
** LEARNING Теорема о произведении мер
   Произведение мер Лебега - это тоже мера Лебега, но суммарной размерности.

   В ℝⁿ всегда выполняется λₐ×λₛ = λₐ₊ₛ

   ▵
   Кажется, это почти очевидно, надо только что-то ляпнуть про лебегово продолжение
   ▿
** LEARNING Принцип Кавальери
   Это о том, что можно находить объем, интегрируя высоту по площади или площадь по высоте.

   (X, ℵ, μ), (Y, ℶ, ν)
   m = ν × μ, μ, ν - σ-конечные, полные
   С ∈ ℵ × ℶ - некая фигура

   Тогда выполнено следующее:
   1. Cₓ - ν-измеримо при п.в. X
   2. x ↦ ν(Cₓ) - μ-измеримая* на X функция
   3. m(C) = ∫ₓ ν(Cₓ)dμ(x)

   ▵
   Делаем как бы по структурной индукции:
   сначала докажем для обобщенных прямоугольников,
   потом для счетных объединений/пересечений,
   потом для всех множеств меры 0,
   потом для всех конечномерных,
   и наконец для всех измеримых.
   ▿
** LEARNING Теорема Тонелли
   Это о том, что интеграл по площади можно разбить на 2 интеграла - по ширине и высоте,
   причем в разном порядке.

   (X, ℵ, μ), (Y, ℶ, ν), μ, ν - σ-конечные, полные, m=μ×ν
   f: X × Y → ℝ, f ≥ 0, измеримая

   Обозначение: fₓ = y ↦ f(x, y)

   Тогда выполнено:
   1. fₓ - ν-измерима при почти всех x
   2. fʸ - μ-измерима при почти всех y
   3. x → φ(x) := ∫fₓdν - μ-измеримaя функция
   4. X×Y_∫ fdm = Y_∫ φ(x) dμ(x) = ∫ (∫f(x, y)dν(y)) dμ(x) = ∫ (∫f(x, y)dμ(x)) dν(y)

   ▵
   Опять подъем: характеристические -> ступенчатые -> полож. измеримые
   Каждый этап доказывается элементарно по принципу Кавальери + опора на предыдущие
   ▿
** LEARNING Формула для Бета-функции
   Β(s, t) = ₀∫¹ xˢ⁻¹ · (1 - x)ᵗ⁻¹ dx = Γ(s)Γ(t)/Γ(s+t)

   ▵
   Рассмотрим Г(s)Г(t) - произведение интегралов. Занесем один под другой,
   объединим в двойной, сделаем 2 замены (y = u - x, x = uz) и все.
   ▿
** LEARNING Теорема Фубини
   Ну, вроде то же самое, что Тонелли, только для произвольной суммируемой функции

   (X, A, μ), (Y, B, ν), μ,ν - σ-конечные, полные, m=μ×ν
   f: X × Y → ℝ~ - m-суммируемая

   Тогда:
   1. fₓ - суммируема п. в. на X, fʸ - сумм. п. в. на Y
   2.
      1. x ↦ φ(x) := ∫fₓdν  - сумм.* на X
      2. y ↦ ψ(y) := ∫fʸdμ  - сумм.* на Y
   3. ∫ fdm = ∫ φ(x)dμ = ∫ ψ(y)dν

   ▵
   Рассмотрим + и - срезки, для них верна теорема Тонелли, оттуда
   все легко выводится
   ▿
** LEARNING Объем шара в ℝⁿ
   V(B(0, r)) = αₙ * r^n
   αₙ = (√π)ⁿ / Γ(n/2 + 1)

   ▵
   Рассмотрим единичный шар: из интеграла для его объема
   вычленим одно изменение и сведем получившееся к B-функции, домноженной
   на объем шара меньшей размерности. Раскроем по индукции и все посокращается.
   ▿
** LEARNING Теорема о вычислении интеграла с помощью меры Бореля-Стилтьеса
   Интеграл некоторой функции (или выражения от нее) можно свести к интегралу
   функции распределения по ℝ

   Лемма:
   (X, ℵ, μ)
   Пусть h - измерима, п. в. конечна.
   H - функция распределения: H(t) = μX(h < t)
   ν = h(μ), то есть: ν(A) = μ(h⁻¹(A))
   μₕ - мера Бореля-Стилтьеса от H
   Тогда:
   μₕ ≡ ν на B (Борелевской σ-алгебре)

   Теорема:
   f : ℝ → ℝ, f ≥ 0, измерима отн. B, остальное то же самое.
   Тогда:
   ∫_X f(h(x))dμ(x) = ∫_ℝ f(t) dμₕ(t)

   ▵
   Лемма: сначала покажем непрерывность функции распределения - она
   следует из непрерывности меры сверху, ну потом напишем по определению
   меры Б-С, пошафлим и получим, что надо.
   Теорема: из леммы и теореме о интегралу по взвешенному образу
   ▿
** LEARNING Теорема о вложении пространств Lᵖ
   В пространстве конечной меры L с большим p вложено в L с меньшим

   (X, ℵ, μ), μX < +∞, 1 ≤ s < r < +∞
   1) Lʳ ⊂ Lˢ
   2) |f|ₛ ≤ (μX)^(1/s - 1/r) · |f|ᵣ

   ▵
   1 пункт следует из 2, а 2 доказываем через неравенство Гельдера для f и 1.
   ▿
** LEARNING Полнота Lᵖ
   Пространство Lᵖ полно.

   ▵
   Возьмем фундаментальную последовательность. Выделим из нее подпоследовательность
   такую, чтобы расстояние м/у соседями сжималось на каждом шаге вдвое. Тогда ряд из
   расстояний сходится (< 1). Возьмем и подставим иксы в этот ряд и докажем, что
   полученная функция почти везде конечна. Но если прибавить к ней еще первый член, то она
   телескопически сложится - так получим кандидата на предел. Аккуратно покажем,
   что этот кандидат конечен и действительно является пределом исходной последовательности
   ▿
** LEARNING Плотность в Lᵖ множества ступенчатых функций
   Множество ступенчатых функций плотно в Lᵖ (включая L∞)

   ▵
   Рассмотрим конечное p и ∞
   В обоих случаях приблизим нашу измеримую ограниченную функцию ступенчатыми,
   распишем норму в Lᵖ и покажем, что она сходится
   ▿

** LEARNING Лемма Урысона
   Для пары непересек. замкнутых множеств существует непрерывная функция,
   которая на одном всегда 0, а на другом - 1.

   F₀, F₁ - замкнутые, непересекающиеся (в ℝᵐ)
   ∃ f - непрерывная, f|_F₀ = 0, f|_F₁ = 1

   ▵
   Понапихаем между этими множествами кучу открытых множеств в двоично-рациональными
   индексами. Возьмем функцию - инфиум от индекса множества, содержащего x, доопределим
   ее что она = 1 на F₁. Докажем что она непрерывна, для этого достаточно показать,
   что прообраз (-∞, s) открыт, а (-∞, t] - замкнут. Подумав, сопоставим этим
   прообразам объединение/пересечение каких-то дв. рациональных множество
   и увидим, что все получилось
   ▿
** LEARNING Плотность в Lᵖ непрерывных финитных функций
   Множество непрерывных финитных функций полно в Lᵖ

   ∀ p: 1 ≤ p < +∞ : C₀(ℝᵐ) - плотно в Lᵖ(ℝᵐ)

   ▵
   Возьмем ступенчатую функцию, которая лежит близко к нужной.
   Каждую ступеньку окружим плотненько с 2 сторон замкнутым и открытым множеством.
   Возьмем разделяющую функцию из леммы Урысона и вычтем ее из харак. функции ступеньки -
   получим что-то очень маленькое. Ну и соберем из таких (очевидно, финитных) функций
   линейную комбинацию, которая тоже будет близка к ступенчатой, а значит, и к целевой.
   ▿

** LEARNING Теорема о непрерывности сдвига
   Сдвиг функции непрерывен аж во всяких Lᵖ

   fₕ = f(x + h) - сдвиг - обладает следующими св-вами:
   1) f - равн. непрерывна на ℝᵐ ⇒ |fₕ - f|∞ → 0 (при h → 0)
   2) f ∈ Lₚ(ℝᵐ), 1 ≤ p < +∞ ⇒ |fₕ - f|ₚ → 0
   3) f ∈ C[0, T] ⇒ |fₙ - f|∞ → 0
   4) f ∈ Lₚ[0, T], 1 ≤ p < +∞ ⇒ |fₕ - f|ₚ → 0

   ▵
   1) легко из определения равн. непрерывности
   3) непрерывная на компакте функция равн. непрерывна на нем - значит, пункт 1
   4) возьмем непрерывную финитную функцию рядом, докажем непрерывность сдвига для нее:
      оценим интеграл сверху супремумом и сведем к пункту 1
   2) возьмем финитную функцию - можем сузить интеграл до компакта, где работает п. 4
   ▿
** LEARNING Теорема о свойствах сходимости в гильбертовом пространстве
   Скалярное произведение сходится, скалярное произведение бесконечно линейно,
   нормы сходящегося ортогонального ряда сходятся

   1) xₙ → x, yₙ → y ⇒ <xₙ, yₙ> → <x, y>
   2) ∑xₙ - сходящийся ряд, тогда <y, ∑xₙ> = ∑<y, xₙ>
   3) ∑xₙ - ортогональный ряд, тогда ∑xₙ - сходится ⇔ ∑|xₙ| - сходится

   ▵
   Доказывается в два плевка, как на линале, только с предельными переходами.
   1) Разобьем разность скалярных произведений так, чтобы xₙ И x оказались в одной скобке,
      раскроем, применим КБШ, получим нужное.
   2) Вместо ряда рассмотрим предел частичных сумм
   3) Квадраты нормы частичных сумм фундаментальны вместе с самими суммами,
      поэтому когда сходится одно, сходится и другое.
   ▿

** LEARNED Теорема о коэффициентах разложения по ортогональной системе
   CLOSED: [2015-06-26 Fri 00:40]
   Ортогональная система линейно независима, и коэффициенты в ее разложении
   являются результатами скалярных произведений на сам вектор, а каждый компонент
   разложения - проекция на 1мерное подпространство

   H - Г.П, {eₙ} - орт. система, x = ∑Cₙeₙ
   1) {eₙ} - ЛНЗ
   2) Cₙ = <x, eₙ>/|eₙ|²
   3) Cₖeₖ - проекция x на 1мерное п/п-во, порожденное eₖ

   ▵
   Все элементарно скалярным домножением на произвольный базисный вектор
   ▿
** LEARNING Теорема о свойствах частичных сумм ряда Фурье. Неравенство Бесселя.
   Частичная сумма ряда Фурье - это проекция на соотв. подпространство, наилучшее
   приближение к x на нем, и оно меньше x

   {eₖ} - ОС, x ∈ H, x = ∑Cₖeₖ
   Sₙ = ∑ᴺCₖeₖ - част. сумма, Lₙ = Lin(e₁ .. eₙ)
   Тогда:
   1) Sₙ - орт. проекция x на Lₙ
   2) |x - Sₙ| = inf |x - y|, y ∈ Lₙ
   3) |Sₙ| ≤ |x|

   ▵
   Все доказывается с полплевка разложением x = z + Sₙ
   ▿
   Неравенство Бесселя: ∑|Cₖ(x)|² · |eₖ| ≤ |x|
** LEARNING Теорема Рисса-Фишера о сумме ряда Фурье. Равентсво Парсеваля
   Для всякой ортогональной системы ряд Фурье сходится, разложение образует проекцию,
   выполнено равенство Парсеваля.

   {eₖ} - ОС в H, x ∈ H
   1) Ряд Фурье x сходится в H
   2) x = ∑Cₖ(x)eₖ + z ⇒ z ⊥ {eₖ}
   3) x = ∑Cₖ(x)eₖ ⇔ |x|² = ∑|Cₖ(x)|²|eₖ|²

   ▵
   Что-то очевидное ваще, 1 - почему-то через нер-во Бесселя,
   2 - домножением на eₖ, 3 - взятием нормы от предела
   ▿
** LEARNING Теорема о характеристике базиса
   Базис замкнут (и обобщенно замкнут!), полон, его лин. оболочка плотна - все это эквивалентно

   H - Г.П., {eₖ} - OC в H. Эквивалентно:
   1) {eₖ} - базис
   2) <x, y> = ∑Cₖ(x)Cₖ(y)|eₖ|²
   3) {eₖ} - замкнута
   4) {eₖ} - полна
   5) Lin{eₖ} - плотна в H

   ▵
   1 -> 2 -> 3 -> 4 -> 1, 4 -> 5 -> 4
   Каждая стрелка какая-то тривиальная шо пздц
   ▿
** LEARNING Лемма о вычислении коэффициентов тригонометрического ряда
   Коэффициенты Фурье функции можно вычислить как соответствующие интегралы от -π до π

   T(x) - тригонометрический ряд, Sₙ(x)  - его част. суммы.
   Пусть ∃ f ∈ L¹[-π, π], Sₙ → f в пр-ве L¹
   Тогда:
   1) aₖ = ∫_{-π}^π f(x)cos(kx) dx
   2) bₖ = ∫_{-π}^π f(x)sin(kx) dx
   3) Cₖ = ∫_{-π}^π f(x)e⁻ⁱᵏˣdx
** LEARNING Теорема Римана-Лебега
   Интеграл функции на тригонометрический член по всему множеству стремится к нулю при росте k.

   E ⊂ ℝ - измеримо, f ∈ L¹(E). Тогда ₑ∫f(x)e⁻ⁱᵏˣ → 0, если k → +∞
   (ₑ∫f(x)cos(kx) → 0, ₑ∫f(x)sin(kx) → 0)
** LEARNING Принцип локализации Римана
   Если функции равны в окрестности некой точки, то их частичные суммы Фурье в
   этой точке стремятся друг к другу.

   f, g ∈ L¹[-π, π], x₀ ∈ [-π, π], ∃ U(x₀) : ∀ x ∈ U(x₀) : f(x) = g(x).
   Тогда Sₙ(f, x₀) - Sₙ(g, x₀) → 0, n → ∞
** LEARNING Признак Дини. Следствия
   Если странный интеграл вокруг некоторой точки с какой-то константой конечен,
   то частичные суммы Фурье этой функции в этой точке стремятся к этой константе.

   f ∈ L¹[-π, π], x₀ ∈ [-π, π], S ∈ ℝ
   Пусть ₀∫ᵖⁱ (|f(x₀ + t) + f(x₀ - t) - 2S|/t)dt - конечен.
   Тогда Sₙ(f, x₀) → S

   Следствие 1:
   Если у функции существуют предел и производная слева и справа от точки,
   то частичные суммы в ней стремятся к среднему значению из двух пределов

   f ∈ L¹[-π, π], x₀ ∈ [-π, π], ∃ f(x₀ - 0), f(x₀ + 0),
   ∃ α± = lim{x → x₀ ± 0} (f(x) - f(x₀ ± 0))/(x - x₀)
   Тогда Sₙ(f, x₀) → 1/2 · (f(x₀ - 0) + f(x₀ + 0))

   Следствие 2:
   Если функция непрерывна в точке и имеет производные слева и справа от нее,
   то частичные суммы сходятся к значению функции в точке.

   f ∈ L¹[-π, π], x₀ ∈ [-π, π], f - непр. в x₀, ∃ α±
   Тогда Sₙ(f, x₀) → f(x₀)
** LEARNING Корректность определения свертки

** LEARNING Свойства свертки функции из Lᵖ с функцией из L^q
   Свертка функций из "сопряженных по параметру" пространств непрерывна
   и не превышает по норме произведения норм функций.

   f ∈ Lᵖ[-π, π], K ∈ L^q[-π, π], 1/p + 1/q = 1, 1 ≤ p < +∞
   Тогда f ⋆ K - непрерывна на [-π, π],
   и |f ⋆ K|₁ ≤ |f|ₚ · |K|_q
** LEARNING Теорема о свойствах аппроксимативной единицы
   Аппроксимативная единица - нейтральный элемент относительно свертки

   Kₕ - a. е, h₀ - ее предельная точка. Тогда:
   1) f ∈ C[-π, π] ⇒ f ⋆ Kₕ ⇉ f при h → h₀
   2) f ∈ Lᵖ[-π, π] ⇒ |f ⋆ Kₕ - f|ₚ → 0
   3) f ∈ L¹, f - непр. в x₀, Kₕ - усиленная а. е.
      Тогда f ⋆ Kₕ - непрерывна в x₀, (f ⋆ Kₕ)(x₀) → f(x₀) при h → h₀
** LEARNING Теорема Коши о перманентности метода средних арифметических
   Cуммa ряда средними арифметическими равна обычной сумме ряда (если та существует)

   ∑aₙ = S ⇒ ∑aₙ (ср. ариф.) = S
** LEARNING Теорема Фейера
   Суммы Фейера функции сходятся к ней.

   σₙ = (1/(n + 1))∑ₖⁿSₖ(f) - сумма Фейера
   Sₙ(f, x) = ₋ₚᵢ∫ᵖⁱf(x + t)Dₙ(t)dt
   σₙ(f, x) = ₋ₚᵢ∫ᵖⁱf(x + t)Фₙ(t)dt

   1) f ∈ C[-π, π] ⇒ σₙ(f, x) ⇉ f(x)
   2) f ∈ Lᵖ[-π, π] ⇒ |σₙ(f, x) - f(x)|ₚ → 0
   3) f ∈ L¹, f - непрерывно в x ⇒ σₙ(f, x) → f(x)

** LEARNING Полнота тригонометрической системы
   1) Тригонометрическая система {1, sinx, cosx, sin2x, cos2x, ...} полна в L²
   2) f ∈ L¹[-π, π], ∀ k aₖ(f), bₖ(f) = 0 (∀ k Cₖ(f) = 0) ⇒ f = 0 почти везде
** LEARNING Формула Грина
   Как Стокс, только для двумерного случая

   D ⊂ ℝ² - компактное, односвязное, с C² - гладкой границей, (P, Q) - гл. векторное поле.
   Граница ∂D ориентирована согласованно стороне D. Тогда

   ∂D_∫Pdx + Qdy = D_∫∫(∂Q/∂x - ∂P/∂y)dxdy
** LEARNING Формула Стокса
   D - прост. глад. 2-мерная пов-ть в ℝ³,
   ∂D - С²-гладкая, (P, Q, R) - гл. векторное поле,
   ориентация границы согласована со стороной.
   Тогда:

   ∂D_∫Pdx + Qdy + Rdx = D_∫∫(R_y' - Q_z')dydz + (P_z' - Rₓ')dzdx + (Qₓ' - P_y')dxdy
** LEARNING Формула Гаусса-Остроградского
   Интеграл по поверхности равен интегралу дивергенции по объему.

   D ⊂ ℝ³, ∂D - ориентированна полем внеш. нормалей.
   (P, Q, R) - гладкое поле в D. Тогда:

   ∂D_∫∫Pdx + Qdy + Rdz = D_∫∫∫(Pₓ' + Q_y' + R_z')dxdydz
** LEARNING Бескоординатное определение ротора
   Ротор - предел интеграла векторного поля по контуру, который стягивается в точку.
** LEARNING Бескоординатное определение дивергенции
   Дивергенция - предел интеграла векторного поля по поверхности, которая стягивается в точку.
** LEARNING Описание соленоидальных полей в терминах дивергенции
   Поле соленоидально, если его дивергенция всюду 0.

   V - гладкое век. поле. Эквивалентно:
   1) V - соленоидально (V = rot B)
   2) div V = 0
